import json
import subprocess
from pathlib import Path

import pytest

from virtool_cli.merge import (
    organize_otus_by_taxid,
    organize_isolates_by_source_name,
    write_cache,
    update_cache,
    get_cache,
    compare_isolates,
    write_isolates,
    OTUInfo,
    IsolateInfo,
    generate_otu_path,
    get_sequences,
    prepare_prompt,
    write_sequences,
    get_accessions_for_unknown_isolate,
)


@pytest.mark.asyncio
async def test_organize_otus_by_taxid():
    source_src_path = Path("./tests/files/source_ref/src")
    target_src_path = Path("./tests/files/target_ref/src")

    otu_paths_by_taxid, no_taxid_found = await organize_otus_by_taxid(
        source_src_path, target_src_path
    )

    assert otu_paths_by_taxid == {
        "665102": [
            OTUInfo(
                ref="target",
                name="Abutilon Brazil virus",
                directory="abutilon_brazil_virus",
            ),
            OTUInfo(
                ref="source",
                name="Abutilon Brazil virus",
                directory="abutilon_brazil_virus",
            ),
        ],
        "438782": [
            OTUInfo(
                ref="target",
                name="Abaca bunchy top virus",
                directory="abaca_bunchy_top_virus",
            ),
            OTUInfo(
                ref="source",
                name="Abaca bunchy top virus",
                directory="abaca_bunchy_top_virus",
            ),
        ],
        "190811": [
            OTUInfo(
                ref="target",
                name="Bamboo mosaic virus satellite RNA",
                directory="bamboo_mosaic_virus_satellite_rna",
            ),
            OTUInfo(
                ref="source",
                name="Bamboo mosaic virus satellite RNA",
                directory="bamboo_mosaic_virus_satellite_rna",
            ),
        ],
        "35286": [
            OTUInfo(
                ref="target",
                name="Bamboo mosaic virus",
                directory="bamboo_mosaic_virus",
            ),
            OTUInfo(
                ref="source",
                name="Bamboo mosaic virus",
                directory="bamboo_mosaic_virus",
            ),
        ],
        "2060511": [
            OTUInfo(
                ref="target",
                name="Babaco mosaic virus",
                directory="babaco_mosaic_virus",
            ),
            OTUInfo(
                ref="source",
                name="Babaco mosaic virus",
                directory="babaco_mosaic_virus",
            ),
        ],
        "345184": [
            OTUInfo(
                ref="source",
                name="Cabbage leaf curl Jamaica virus",
                directory="cabbage_leaf_curl_jamaica_virus",
            )
        ],
        "37127": [
            OTUInfo(
                ref="source",
                name="Citrus variegation virus",
                directory="citrus_variegation_virus",
            )
        ],
    }

    assert no_taxid_found == [
        {
            "_id": "foobar",
            "name": "test",
            "abbreviation": "",
            "schema": [{"name": "foo", "molecule": "bar", "required": True}],
            "taxid": None,
        }
    ]


@pytest.mark.asyncio
async def test_organize_isolates_by_source_name():
    otu_infos = [
        OTUInfo(
            ref="target",
            name="Abutilon Brazil virus",
            directory="abutilon_brazil_virus",
        ),
        OTUInfo(
            ref="source",
            name="Abutilon Brazil virus",
            directory="abutilon_brazil_virus",
        ),
    ]

    result, unknown_isolates = await organize_isolates_by_source_name(
        otu_infos,
        Path("./tests/files/source_ref/src"),
        Path("./tests/files/target_ref/src"),
        "665102",
        False,
    )

    expected = {
        "unknown": [
            IsolateInfo(
                ref="target",
                otu_name="Abutilon Brazil virus",
                id="un404hxp",
                isolate={
                    "id": "un404hxp",
                    "source_type": "unknown",
                    "source_name": "unknown",
                    "default": True,
                },
                sequences=[
                    {
                        "_id": "erdxaihh",
                        "accession": "NC_014138",
                        "definition": "Abutilon Brazil virus DNA A, complete genome",
                        "host": "Abutilon sp.",
                        "sequence": "ACCGGATGGCCGCGCGATTTTTTTAACCCCCCACGTGGCGCATTCCTGGTCGCGCGATCCCCCTCCCCCGCGCGCTTCTCTCCTTTAATTTTAATTAAAGTGCCTAACTTTCTACTGAGCCAATCATATTGCGCCTGACGAGTCTAGATATGTGGGAAAGACTTGGGCCCTAAGTTGTTGATTAACGGCTATAAATTAAAGGAAGACTGGTCACAGTCTTTAATTCAAGATGCCTAAGCGGGATGCCCCTTGGCGCCTTATGGCGGGAACTTCGAAGATTAGCCGTTCCTCTAATACCGGCCCTCGTGGAGGTTCTGGGCCTAAATTCAATAAGGCCAATGAGTGGGTCAACAGGCCAATGTACAGGAAGCCCAGGATATACCGGGCCTTCAGAACTCCAGATGTCCCTCGAGGGTGTGAAGGGCCTTGCAAGGTCCAGTCGTACGAACAGCGACACGACATCTCACATGTCGGCAAGGTCATGTGTATATCTGATATCACCCGAGGTAACGGTATTACTCACCGTGTGGGTAAGCGCTTCTGTGTTAAGTCTGTGTATATTTTAGGTAAGGTATGGATGGACGAGAATATCAAGCTCAAGAACCACACGAACAGTTGCATGTTCTGGCTAGTCAGGGACCGTAGACCGTATGGTACACCCATGGACTTTGGCCAGGTGTTCAACATGTTCGACAACGAGCCCAGTACTGCAACCGTGAAGAACGATCTCCGCGATCGTTTCCAGGTCATGCACAAGTTCTATGCCAAGGTTACTGGTGGTCAGTATGCCAGCAACGAGCAGGCTCTGGTCAAGAGATTCTGGAAGGTCAACAATCATGTGGTCTACAATCACCAAGAGGCCGGGAAGTACGAGAATCATACGGAGAACGCACTATTACTGTATATGGCATGTACCCATGCCTCTAACCCCGTGTATGCAACGCTCAAGATTCGGATCTATTTTTATGATTCGATCACAAATTAATAAAATTTGAATTTTATTGAATGATTTTCCAGTACATGATTGACATACGACTTGTCTGTTGCGAAACGAACAGCTCTAATTACATTATTAAGCGCAATTACACCTAATTGCTCTAAGTACAGCATGACTAAGTGCTTAAATCTAGCTAAATAAGTCTTCCCAGAAGCTGTCAGAGAAGTCGTCCAGACTTGGAAGTTCAGGAATGCCTTGTGGAGACCCAATGCTCTCCTGAGGTTGTGGTTGAACCTTATCTGGATGTGGTACACTCTTGTCCGAGTGTACGGTGGATCCTCTACCCTGTACATCTTGAAATACAGGGGATTTGTTATCTCCCAGATATAGACGCCATTCTCTACCTGACGTGCAGTGATGAGTTCCCCTGTGCGTGAATCCATGGCCTGTGCAGTTGAGATGCTGGTAAATGGAGCAGCCGCAGTCCAGATCAATTCGTCGTCGTCTGATTGCTCTCTTCTTCGCAATCCTGTGTCGTGGTTTGATAGAGGGGGGAGTTGAGGAAGATGAATTTAGCATTGTGTATTGTCCAGGCTTTTAGTGATGAGTTTTCCTGCTTGTCCAGGAAATCTTTATAGCTGGCCCCCTCTCCAGGATTGCAGAGCACGATTGATGGGATACCCCCTTTAATTTGAACAGGCTTGCCGTACTTGCAATTGGACTGCCAATCTTTTTGAGCACCAATCAATTCCTTCCAGTGCTTTAGCTTTAGGTATTGCGGGCTGACATCATCGATGACGTTATACTCAACTTGATTTGAGTAGACCCGGGAATTGAAATCTAAATGGCCACTCAAGTAATTATGTGGGCCTAACGCACGAGCCCACATCGTCTTACCAGTTCGAGAATCACCTTCTACAATCAAACTGATGGGCCTGATAGGCCGCGCAGCGGAACCTCTCCCAAAATAATCATCCGCCCATTCCTGCATCTCTTCCGGAACGTTAGTGAACGATGAGAGGGGAAACGGTGGAGCCCACGGTTCCGGAGCCTTTGTAAAGATCTTTTCTAGGTTGGAGCGGATGTTATGGTGTTGGACGATGAATGACTTTGGATCTCCGGCTCTGATAATTTCAAGAGCCTCTGAAACACCTCCTGCATTGACGGCGTTGTGGAAGACATCGTCCTTGTTGGCCTTGGTACCCCCAGACACTTTGTATTGTCCGGATTCACAATAGTCACCATCTTTGGTGATGTAGTTCCTGACGGCAACGGTGTCTTTGGCAGCTTGCACGTTTGGGTGAAAACTGGCTGACCGTCTGGGGTGAGTAAAGTCGAAAAATCTTGCATCCTTGATGTTGGACTTCCCTGATAATTGTATGAGACAGTGTAGATGGGGGTTTCCATCGGAGTGTTCCTCACGTGCGACTCTGATATAGGTAGGTTGGACGACTGCCCATGGAAGGGCTTGAAGCATTTGAAGAGCTTCATCTTTGGGTATGTCGCATCGCGGATATGTGAGGAATATGTTTCTGGCTTGTAATCTAAAAGAATGGGGAAGTCGGGGCATATTTGTAAATTTATGTTCAGGACTCCAGCCCAGGACTCCAGGGGAGCTCTCAACTTCTGTCATATTTGCTGGAGTCCTGGAGTCCCATTTATACTACAACTCTCTAAGGCTCTTAGGGGGCACGTGGCGGCCATCCGTATAATATT",
                    },
                    {
                        "_id": "nm5iylku",
                        "accession": "NC_014139",
                        "definition": "Abutilon Brazil virus DNA B, complete genome",
                        "host": "Abutilon sp.",
                        "sequence": "ACCGGATGGCCGCGCGATTTTCCCCCCCCGCTCACGTGGCGCGCTCCTCTCCCTCCGATCTTCGTCCGCAACACGTGGCTTTGTGTTGCTCGCTCTATCCCGCTGGTCCCAATTTAGTTTAGCGCTATTTTGAAGTCCGCGAAATGAGCTGAGCGCATTTTTTGAGATCCGCCAACGGTATGCCGACATGTGGAATATTTGACTGCTTTGACTGTACTGGCGGACTTCTCTTTTTTATTTTTTGTGATTTATTTAAGACCGTTGGATAAAAATAAAAAATTTTGAAATTTGAATTATCGTGGCGCTGTCTGCCACTAAAGGAATATGGATGACCAATTATCTCTCGAGTTACAACCTTTAGGCATTGCGACGTGGCGCAATGAATTACCAATGGCTGAGGCAAAATAAGTTAGTATCGATTGGGAAATTTATGTATAAATTTCATCTGGATAAGTATTAGAAGATATAGTTTATACTTGGAAATAATTTCAAAATGTATTCGATCAAACACAAACGTGGTGTGTCTTCTACGTACCGGCGTAGTTATGCAAGGAATCCGTTATCCAAGCGTTCTTACGCCGTGAGACGCACCGATCGTAAACATCGGTCGAGTACTGTGAACAAGGCGCCGGAAGATGGTAAAATGACAGGTCAGCGTATGCACGAGAATCAGTTTGGGCCTGATTTTGTGATGGGCCATAATGCAGCCATATCCACGTATATCACCTACCCTGCTCTTGGTAAGAGTGAACCCAACAGGTCCAGGTCGTATATTAAGTTGAAACGTCTACGTTTCAAGGGTACTGTGAAGATAGAACGTGTACATGTGGATGTGAACATGGATGGAGTATCCCCGAAGATCGAAGGAGTATTTTCCATGGTCGTGGTCGTGGATCGTAAACCCCATTTGGGTCCGTCTGGATGTCTACCCACGTTTGATGAGTTATTCGGTGCAAGAATCCACAGCCATGGAAATTTGGCCATAACATCGTCCCTGAAAGACCGTTTCTATATTCGACATGTGCACAAACATGTGCTGTCGGTCGAGAAGGATAGCTTGATGGTAGACCTCGAAGGGACGAACTCTCTCTCTAGCAGGCGTTTTAACTGTTGGGCTAGCTTTAAGGACATTGACCGTGATTCATGTAACGGTGTTTATGCAAACATAAGCAAGAACGCCCTGTTAGTTTATTATTGTTGGATGTCGGACTCGTCGTCCAAGGCATCGACATTTGTATCGTTTGATCTGGATTATATTGGCTAAGAATAATAATTTATTTCAATACATGATAATGGCTTAGGATCTCGACAATTATGTTTATTATCTCAAAGACTTGGGCTCGGAGGGAGTGCAATTTGTGTTAATACACTCTTGGACCGTACTCCGAACAAGCTCGTTCAGTTGGGCCATTGACATGGTTATGTTGGACTGTGCCCTCTGGGCCCCGACAATTGAAGCAGAATCACCTGGGTCTAACATGGTGGTGCCCAACCTATGCAGCCCTCGATACGGGTGTGCTGCGATCTCCACCTCGGAGTCCGTTGTAGATTGACCGGTCCCTATGGTACTTCTGTGAGCCCAGGTCTCACCTGGATCAATTGATATTGGGCCTGGAAGCCCATGATTGACTGTTGATATGGATCGGATCAATTTCCTTTCCCATTTACCATAGCCCACATGGCAGAAGTCTATGTCTCTGTCTGTGAACTGTTTAGATAAGATCTTAACTGTCGGTGCTCGGAAAGGAATATCGACAGAATGTTTCGCCGTCGACAACTTTAGCTTGCCCTTGAACTTCGCGAAGTGGGTCCTCTGATGAACATTCGTGTCGCTAACCCTGTAATATAGTTTCCATGGGACTGGATCCTTCAGGGAGAAGAACGACGATGAGAAATAGTGGAGGTCGATGTTACACCGGATCGGGAATGTCCATGACGCCTGTAAGGATTCATTGTCCGTCATCCTCTTGTCGTGAATCTCCACGATGACGGAACCTGCGGCGTTTATGGGTACCTGCTGTCTGTATTCTATGACGCAATGGTCGATCTTCATACAGCTACGACTGAGCCTGGCGCTTATCTGAGCCGCCGCAGATGGAAACTGTAGTACGATCTCAGTTAGGTCGTGGGAAAGTTGATACTCATCACGCTGAGATTCTATATAATTAAAGGCATTTGGTGGATTAACTAACTGAGACTCCATTATTTAAGTTAAGAAGAATAGGCCGCGCAGCGGAATGTTTAGGCGAATTGGACAAGGTTATAATTGAAGGGGGAAGAAGACCTGAGTAAAATGAAAGAGTAAAGTGAAAGAGTAAAGTGAATAAGGTCGAAAGAAATGAGGGTTCCGGCAAGGTATAAATCCCGTGGACGGATTGAGAGGAGATATGAAAGAGGAAGTTGTTTTGCAATTTGTGCCTGATATGTCCTGTTTAAATAGACAGCGTCTGGAACGACTATTCATCGAATGGCATAAATGTAAATAAGACGGGGACTCCAACCCAGGACTCCAGGGGAGCTCTTAACTTCTGTCATATTTGCTGGAGTCCTGGAGTCCCATTTATACTACAACTCTCTAAGGCTCTTAGGGGGCACGTGGCGGCCATCCGTATAATATT",
                    },
                ],
                taxid="665102",
            ),
            IsolateInfo(
                ref="source",
                otu_name="Abutilon Brazil virus",
                id="un404hxp",
                isolate={
                    "id": "un404hxp",
                    "source_type": "unknown",
                    "source_name": "unknown",
                    "default": True,
                },
                sequences=[
                    {
                        "_id": "NC_014138",
                        "accession": "NC_014138",
                        "definition": "Abutilon Brazil virus DNA A, complete genome",
                        "host": "Abutilon sp.",
                        "sequence": "ACCGGATGGCCGCGCGATTTTTTTAACCCCCCACGTGGCGCATTCCTGGTCGCGCGATCCCCCTCCCCCGCGCGCTTCTCTCCTTTAATTTTAATTAAAGTGCCTAACTTTCTACTGAGCCAATCATATTGCGCCTGACGAGTCTAGATATGTGGGAAAGACTTGGGCCCTAAGTTGTTGATTAACGGCTATAAATTAAAGGAAGACTGGTCACAGTCTTTAATTCAAGATGCCTAAGCGGGATGCCCCTTGGCGCCTTATGGCGGGAACTTCGAAGATTAGCCGTTCCTCTAATACCGGCCCTCGTGGAGGTTCTGGGCCTAAATTCAATAAGGCCAATGAGTGGGTCAACAGGCCAATGTACAGGAAGCCCAGGATATACCGGGCCTTCAGAACTCCAGATGTCCCTCGAGGGTGTGAAGGGCCTTGCAAGGTCCAGTCGTACGAACAGCGACACGACATCTCACATGTCGGCAAGGTCATGTGTATATCTGATATCACCCGAGGTAACGGTATTACTCACCGTGTGGGTAAGCGCTTCTGTGTTAAGTCTGTGTATATTTTAGGTAAGGTATGGATGGACGAGAATATCAAGCTCAAGAACCACACGAACAGTTGCATGTTCTGGCTAGTCAGGGACCGTAGACCGTATGGTACACCCATGGACTTTGGCCAGGTGTTCAACATGTTCGACAACGAGCCCAGTACTGCAACCGTGAAGAACGATCTCCGCGATCGTTTCCAGGTCATGCACAAGTTCTATGCCAAGGTTACTGGTGGTCAGTATGCCAGCAACGAGCAGGCTCTGGTCAAGAGATTCTGGAAGGTCAACAATCATGTGGTCTACAATCACCAAGAGGCCGGGAAGTACGAGAATCATACGGAGAACGCACTATTACTGTATATGGCATGTACCCATGCCTCTAACCCCGTGTATGCAACGCTCAAGATTCGGATCTATTTTTATGATTCGATCACAAATTAATAAAATTTGAATTTTATTGAATGATTTTCCAGTACATGATTGACATACGACTTGTCTGTTGCGAAACGAACAGCTCTAATTACATTATTAAGCGCAATTACACCTAATTGCTCTAAGTACAGCATGACTAAGTGCTTAAATCTAGCTAAATAAGTCTTCCCAGAAGCTGTCAGAGAAGTCGTCCAGACTTGGAAGTTCAGGAATGCCTTGTGGAGACCCAATGCTCTCCTGAGGTTGTGGTTGAACCTTATCTGGATGTGGTACACTCTTGTCCGAGTGTACGGTGGATCCTCTACCCTGTACATCTTGAAATACAGGGGATTTGTTATCTCCCAGATATAGACGCCATTCTCTACCTGACGTGCAGTGATGAGTTCCCCTGTGCGTGAATCCATGGCCTGTGCAGTTGAGATGCTGGTAAATGGAGCAGCCGCAGTCCAGATCAATTCGTCGTCGTCTGATTGCTCTCTTCTTCGCAATCCTGTGTCGTGGTTTGATAGAGGGGGGAGTTGAGGAAGATGAATTTAGCATTGTGTATTGTCCAGGCTTTTAGTGATGAGTTTTCCTGCTTGTCCAGGAAATCTTTATAGCTGGCCCCCTCTCCAGGATTGCAGAGCACGATTGATGGGATACCCCCTTTAATTTGAACAGGCTTGCCGTACTTGCAATTGGACTGCCAATCTTTTTGAGCACCAATCAATTCCTTCCAGTGCTTTAGCTTTAGGTATTGCGGGCTGACATCATCGATGACGTTATACTCAACTTGATTTGAGTAGACCCGGGAATTGAAATCTAAATGGCCACTCAAGTAATTATGTGGGCCTAACGCACGAGCCCACATCGTCTTACCAGTTCGAGAATCACCTTCTACAATCAAACTGATGGGCCTGATAGGCCGCGCAGCGGAACCTCTCCCAAAATAATCATCCGCCCATTCCTGCATCTCTTCCGGAACGTTAGTGAACGATGAGAGGGGAAACGGTGGAGCCCACGGTTCCGGAGCCTTTGTAAAGATCTTTTCTAGGTTGGAGCGGATGTTATGGTGTTGGACGATGAATGACTTTGGATCTCCGGCTCTGATAATTTCAAGAGCCTCTGAAACACCTCCTGCATTGACGGCGTTGTGGAAGACATCGTCCTTGTTGGCCTTGGTACCCCCAGACACTTTGTATTGTCCGGATTCACAATAGTCACCATCTTTGGTGATGTAGTTCCTGACGGCAACGGTGTCTTTGGCAGCTTGCACGTTTGGGTGAAAACTGGCTGACCGTCTGGGGTGAGTAAAGTCGAAAAATCTTGCATCCTTGATGTTGGACTTCCCTGATAATTGTATGAGACAGTGTAGATGGGGGTTTCCATCGGAGTGTTCCTCACGTGCGACTCTGATATAGGTAGGTTGGACGACTGCCCATGGAAGGGCTTGAAGCATTTGAAGAGCTTCATCTTTGGGTATGTCGCATCGCGGATATGTGAGGAATATGTTTCTGGCTTGTAATCTAAAAGAATGGGGAAGTCGGGGCATATTTGTAAATTTATGTTCAGGACTCCAGCCCAGGACTCCAGGGGAGCTCTCAACTTCTGTCATATTTGCTGGAGTCCTGGAGTCCCATTTATACTACAACTCTCTAAGGCTCTTAGGGGGCACGTGGCGGCCATCCGTATAATATT",
                    },
                    {
                        "_id": "NC_014139",
                        "accession": "NC_014139",
                        "definition": "Abutilon Brazil virus DNA B, complete genome",
                        "host": "Abutilon sp.",
                        "sequence": "ACCGGATGGCCGCGCGATTTTCCCCCCCCGCTCACGTGGCGCGCTCCTCTCCCTCCGATCTTCGTCCGCAACACGTGGCTTTGTGTTGCTCGCTCTATCCCGCTGGTCCCAATTTAGTTTAGCGCTATTTTGAAGTCCGCGAAATGAGCTGAGCGCATTTTTTGAGATCCGCCAACGGTATGCCGACATGTGGAATATTTGACTGCTTTGACTGTACTGGCGGACTTCTCTTTTTTATTTTTTGTGATTTATTTAAGACCGTTGGATAAAAATAAAAAATTTTGAAATTTGAATTATCGTGGCGCTGTCTGCCACTAAAGGAATATGGATGACCAATTATCTCTCGAGTTACAACCTTTAGGCATTGCGACGTGGCGCAATGAATTACCAATGGCTGAGGCAAAATAAGTTAGTATCGATTGGGAAATTTATGTATAAATTTCATCTGGATAAGTATTAGAAGATATAGTTTATACTTGGAAATAATTTCAAAATGTATTCGATCAAACACAAACGTGGTGTGTCTTCTACGTACCGGCGTAGTTATGCAAGGAATCCGTTATCCAAGCGTTCTTACGCCGTGAGACGCACCGATCGTAAACATCGGTCGAGTACTGTGAACAAGGCGCCGGAAGATGGTAAAATGACAGGTCAGCGTATGCACGAGAATCAGTTTGGGCCTGATTTTGTGATGGGCCATAATGCAGCCATATCCACGTATATCACCTACCCTGCTCTTGGTAAGAGTGAACCCAACAGGTCCAGGTCGTATATTAAGTTGAAACGTCTACGTTTCAAGGGTACTGTGAAGATAGAACGTGTACATGTGGATGTGAACATGGATGGAGTATCCCCGAAGATCGAAGGAGTATTTTCCATGGTCGTGGTCGTGGATCGTAAACCCCATTTGGGTCCGTCTGGATGTCTACCCACGTTTGATGAGTTATTCGGTGCAAGAATCCACAGCCATGGAAATTTGGCCATAACATCGTCCCTGAAAGACCGTTTCTATATTCGACATGTGCACAAACATGTGCTGTCGGTCGAGAAGGATAGCTTGATGGTAGACCTCGAAGGGACGAACTCTCTCTCTAGCAGGCGTTTTAACTGTTGGGCTAGCTTTAAGGACATTGACCGTGATTCATGTAACGGTGTTTATGCAAACATAAGCAAGAACGCCCTGTTAGTTTATTATTGTTGGATGTCGGACTCGTCGTCCAAGGCATCGACATTTGTATCGTTTGATCTGGATTATATTGGCTAAGAATAATAATTTATTTCAATACATGATAATGGCTTAGGATCTCGACAATTATGTTTATTATCTCAAAGACTTGGGCTCGGAGGGAGTGCAATTTGTGTTAATACACTCTTGGACCGTACTCCGAACAAGCTCGTTCAGTTGGGCCATTGACATGGTTATGTTGGACTGTGCCCTCTGGGCCCCGACAATTGAAGCAGAATCACCTGGGTCTAACATGGTGGTGCCCAACCTATGCAGCCCTCGATACGGGTGTGCTGCGATCTCCACCTCGGAGTCCGTTGTAGATTGACCGGTCCCTATGGTACTTCTGTGAGCCCAGGTCTCACCTGGATCAATTGATATTGGGCCTGGAAGCCCATGATTGACTGTTGATATGGATCGGATCAATTTCCTTTCCCATTTACCATAGCCCACATGGCAGAAGTCTATGTCTCTGTCTGTGAACTGTTTAGATAAGATCTTAACTGTCGGTGCTCGGAAAGGAATATCGACAGAATGTTTCGCCGTCGACAACTTTAGCTTGCCCTTGAACTTCGCGAAGTGGGTCCTCTGATGAACATTCGTGTCGCTAACCCTGTAATATAGTTTCCATGGGACTGGATCCTTCAGGGAGAAGAACGACGATGAGAAATAGTGGAGGTCGATGTTACACCGGATCGGGAATGTCCATGACGCCTGTAAGGATTCATTGTCCGTCATCCTCTTGTCGTGAATCTCCACGATGACGGAACCTGCGGCGTTTATGGGTACCTGCTGTCTGTATTCTATGACGCAATGGTCGATCTTCATACAGCTACGACTGAGCCTGGCGCTTATCTGAGCCGCCGCAGATGGAAACTGTAGTACGATCTCAGTTAGGTCGTGGGAAAGTTGATACTCATCACGCTGAGATTCTATATAATTAAAGGCATTTGGTGGATTAACTAACTGAGACTCCATTATTTAAGTTAAGAAGAATAGGCCGCGCAGCGGAATGTTTAGGCGAATTGGACAAGGTTATAATTGAAGGGGGAAGAAGACCTGAGTAAAATGAAAGAGTAAAGTGAAAGAGTAAAGTGAATAAGGTCGAAAGAAATGAGGGTTCCGGCAAGGTATAAATCCCGTGGACGGATTGAGAGGAGATATGAAAGAGGAAGTTGTTTTGCAATTTGTGCCTGATATGTCCTGTTTAAATAGACAGCGTCTGGAACGACTATTCATCGAATGGCATAAATGTAAATAAGACGGGGACTCCAACCCAGGACTCCAGGGGAGCTCTTAACTTCTGTCATATTTGCTGGAGTCCTGGAGTCCCATTTATACTACAACTCTCTAAGGCTCTTAGGGGGCACGTGGCGGCCATCCGTATAATATT",
                    },
                ],
                taxid="665102",
            ),
        ]
    }

    assert result == expected


@pytest.mark.asyncio
async def test_get_accessions_for_unkown_isolate():
    isolate_path = Path("./tests/files/source_ref/src/a/abutilon_brazil_virus/un404hxp")

    result = await get_accessions_for_unknown_isolate(isolate_path)

    assert result == ["NC_014138", "NC_014139"]


def test_write_unknown_isolates(mocker):
    mocker.patch("rich.prompt.Prompt.ask", return_value="Y")

    command = [
        "virtool",
        "ref",
        "merge",
        "-s",
        "./tests/files/source_ref/src",
        "-t",
        "./tests/files/target_ref/src",
        "--output-unknown-isolates",
    ]

    subprocess.call(command)

    with open(Path("./tests/files/unknown_isolates.txt"), "r") as f:
        result = f.read()

    assert (
        result == "Abutilon  Brazil  virus\tun404hxp\t['NC_014138',  'NC_014139']\n"
        "Abutilon  Brazil  virus\tun404hxp\t['NC_014138',  'NC_014139']\n"
    )


def test_generate_otu_path():
    otu_info = OTUInfo(
        ref="target",
        name="Abutilon Brazil virus",
        directory="abutilon_brazil_virus",
    )

    result = generate_otu_path(
        otu_info,
        Path("./tests/files/source_ref/src"),
        Path("./tests/files/target_ref/src"),
    )
    assert result == Path("tests/files/target_ref/src/a/abutilon_brazil_virus")


@pytest.mark.asyncio
async def test_get_sequences():
    otu_path = Path("tests/files/target_ref/src/a/abutilon_brazil_virus/un404hxp")

    result = await get_sequences(otu_path)
    sequences = [
        {
            "_id": "erdxaihh",
            "accession": "NC_014138",
            "definition": "Abutilon Brazil virus DNA A, complete genome",
            "host": "Abutilon sp.",
            "sequence": "ACCGGATGGCCGCGCGATTTTTTTAACCCCCCACGTGGCGCATTCCTGGTCGCGCGATCCCCCTCCCCCGCGCGCTTCTCTCCTTTAATTTTAATTAAAGTGCCTAACTTTCTACTGAGCCAATCATATTGCGCCTGACGAGTCTAGATATGTGGGAAAGACTTGGGCCCTAAGTTGTTGATTAACGGCTATAAATTAAAGGAAGACTGGTCACAGTCTTTAATTCAAGATGCCTAAGCGGGATGCCCCTTGGCGCCTTATGGCGGGAACTTCGAAGATTAGCCGTTCCTCTAATACCGGCCCTCGTGGAGGTTCTGGGCCTAAATTCAATAAGGCCAATGAGTGGGTCAACAGGCCAATGTACAGGAAGCCCAGGATATACCGGGCCTTCAGAACTCCAGATGTCCCTCGAGGGTGTGAAGGGCCTTGCAAGGTCCAGTCGTACGAACAGCGACACGACATCTCACATGTCGGCAAGGTCATGTGTATATCTGATATCACCCGAGGTAACGGTATTACTCACCGTGTGGGTAAGCGCTTCTGTGTTAAGTCTGTGTATATTTTAGGTAAGGTATGGATGGACGAGAATATCAAGCTCAAGAACCACACGAACAGTTGCATGTTCTGGCTAGTCAGGGACCGTAGACCGTATGGTACACCCATGGACTTTGGCCAGGTGTTCAACATGTTCGACAACGAGCCCAGTACTGCAACCGTGAAGAACGATCTCCGCGATCGTTTCCAGGTCATGCACAAGTTCTATGCCAAGGTTACTGGTGGTCAGTATGCCAGCAACGAGCAGGCTCTGGTCAAGAGATTCTGGAAGGTCAACAATCATGTGGTCTACAATCACCAAGAGGCCGGGAAGTACGAGAATCATACGGAGAACGCACTATTACTGTATATGGCATGTACCCATGCCTCTAACCCCGTGTATGCAACGCTCAAGATTCGGATCTATTTTTATGATTCGATCACAAATTAATAAAATTTGAATTTTATTGAATGATTTTCCAGTACATGATTGACATACGACTTGTCTGTTGCGAAACGAACAGCTCTAATTACATTATTAAGCGCAATTACACCTAATTGCTCTAAGTACAGCATGACTAAGTGCTTAAATCTAGCTAAATAAGTCTTCCCAGAAGCTGTCAGAGAAGTCGTCCAGACTTGGAAGTTCAGGAATGCCTTGTGGAGACCCAATGCTCTCCTGAGGTTGTGGTTGAACCTTATCTGGATGTGGTACACTCTTGTCCGAGTGTACGGTGGATCCTCTACCCTGTACATCTTGAAATACAGGGGATTTGTTATCTCCCAGATATAGACGCCATTCTCTACCTGACGTGCAGTGATGAGTTCCCCTGTGCGTGAATCCATGGCCTGTGCAGTTGAGATGCTGGTAAATGGAGCAGCCGCAGTCCAGATCAATTCGTCGTCGTCTGATTGCTCTCTTCTTCGCAATCCTGTGTCGTGGTTTGATAGAGGGGGGAGTTGAGGAAGATGAATTTAGCATTGTGTATTGTCCAGGCTTTTAGTGATGAGTTTTCCTGCTTGTCCAGGAAATCTTTATAGCTGGCCCCCTCTCCAGGATTGCAGAGCACGATTGATGGGATACCCCCTTTAATTTGAACAGGCTTGCCGTACTTGCAATTGGACTGCCAATCTTTTTGAGCACCAATCAATTCCTTCCAGTGCTTTAGCTTTAGGTATTGCGGGCTGACATCATCGATGACGTTATACTCAACTTGATTTGAGTAGACCCGGGAATTGAAATCTAAATGGCCACTCAAGTAATTATGTGGGCCTAACGCACGAGCCCACATCGTCTTACCAGTTCGAGAATCACCTTCTACAATCAAACTGATGGGCCTGATAGGCCGCGCAGCGGAACCTCTCCCAAAATAATCATCCGCCCATTCCTGCATCTCTTCCGGAACGTTAGTGAACGATGAGAGGGGAAACGGTGGAGCCCACGGTTCCGGAGCCTTTGTAAAGATCTTTTCTAGGTTGGAGCGGATGTTATGGTGTTGGACGATGAATGACTTTGGATCTCCGGCTCTGATAATTTCAAGAGCCTCTGAAACACCTCCTGCATTGACGGCGTTGTGGAAGACATCGTCCTTGTTGGCCTTGGTACCCCCAGACACTTTGTATTGTCCGGATTCACAATAGTCACCATCTTTGGTGATGTAGTTCCTGACGGCAACGGTGTCTTTGGCAGCTTGCACGTTTGGGTGAAAACTGGCTGACCGTCTGGGGTGAGTAAAGTCGAAAAATCTTGCATCCTTGATGTTGGACTTCCCTGATAATTGTATGAGACAGTGTAGATGGGGGTTTCCATCGGAGTGTTCCTCACGTGCGACTCTGATATAGGTAGGTTGGACGACTGCCCATGGAAGGGCTTGAAGCATTTGAAGAGCTTCATCTTTGGGTATGTCGCATCGCGGATATGTGAGGAATATGTTTCTGGCTTGTAATCTAAAAGAATGGGGAAGTCGGGGCATATTTGTAAATTTATGTTCAGGACTCCAGCCCAGGACTCCAGGGGAGCTCTCAACTTCTGTCATATTTGCTGGAGTCCTGGAGTCCCATTTATACTACAACTCTCTAAGGCTCTTAGGGGGCACGTGGCGGCCATCCGTATAATATT",
        },
        {
            "_id": "nm5iylku",
            "accession": "NC_014139",
            "definition": "Abutilon Brazil virus DNA B, complete genome",
            "host": "Abutilon sp.",
            "sequence": "ACCGGATGGCCGCGCGATTTTCCCCCCCCGCTCACGTGGCGCGCTCCTCTCCCTCCGATCTTCGTCCGCAACACGTGGCTTTGTGTTGCTCGCTCTATCCCGCTGGTCCCAATTTAGTTTAGCGCTATTTTGAAGTCCGCGAAATGAGCTGAGCGCATTTTTTGAGATCCGCCAACGGTATGCCGACATGTGGAATATTTGACTGCTTTGACTGTACTGGCGGACTTCTCTTTTTTATTTTTTGTGATTTATTTAAGACCGTTGGATAAAAATAAAAAATTTTGAAATTTGAATTATCGTGGCGCTGTCTGCCACTAAAGGAATATGGATGACCAATTATCTCTCGAGTTACAACCTTTAGGCATTGCGACGTGGCGCAATGAATTACCAATGGCTGAGGCAAAATAAGTTAGTATCGATTGGGAAATTTATGTATAAATTTCATCTGGATAAGTATTAGAAGATATAGTTTATACTTGGAAATAATTTCAAAATGTATTCGATCAAACACAAACGTGGTGTGTCTTCTACGTACCGGCGTAGTTATGCAAGGAATCCGTTATCCAAGCGTTCTTACGCCGTGAGACGCACCGATCGTAAACATCGGTCGAGTACTGTGAACAAGGCGCCGGAAGATGGTAAAATGACAGGTCAGCGTATGCACGAGAATCAGTTTGGGCCTGATTTTGTGATGGGCCATAATGCAGCCATATCCACGTATATCACCTACCCTGCTCTTGGTAAGAGTGAACCCAACAGGTCCAGGTCGTATATTAAGTTGAAACGTCTACGTTTCAAGGGTACTGTGAAGATAGAACGTGTACATGTGGATGTGAACATGGATGGAGTATCCCCGAAGATCGAAGGAGTATTTTCCATGGTCGTGGTCGTGGATCGTAAACCCCATTTGGGTCCGTCTGGATGTCTACCCACGTTTGATGAGTTATTCGGTGCAAGAATCCACAGCCATGGAAATTTGGCCATAACATCGTCCCTGAAAGACCGTTTCTATATTCGACATGTGCACAAACATGTGCTGTCGGTCGAGAAGGATAGCTTGATGGTAGACCTCGAAGGGACGAACTCTCTCTCTAGCAGGCGTTTTAACTGTTGGGCTAGCTTTAAGGACATTGACCGTGATTCATGTAACGGTGTTTATGCAAACATAAGCAAGAACGCCCTGTTAGTTTATTATTGTTGGATGTCGGACTCGTCGTCCAAGGCATCGACATTTGTATCGTTTGATCTGGATTATATTGGCTAAGAATAATAATTTATTTCAATACATGATAATGGCTTAGGATCTCGACAATTATGTTTATTATCTCAAAGACTTGGGCTCGGAGGGAGTGCAATTTGTGTTAATACACTCTTGGACCGTACTCCGAACAAGCTCGTTCAGTTGGGCCATTGACATGGTTATGTTGGACTGTGCCCTCTGGGCCCCGACAATTGAAGCAGAATCACCTGGGTCTAACATGGTGGTGCCCAACCTATGCAGCCCTCGATACGGGTGTGCTGCGATCTCCACCTCGGAGTCCGTTGTAGATTGACCGGTCCCTATGGTACTTCTGTGAGCCCAGGTCTCACCTGGATCAATTGATATTGGGCCTGGAAGCCCATGATTGACTGTTGATATGGATCGGATCAATTTCCTTTCCCATTTACCATAGCCCACATGGCAGAAGTCTATGTCTCTGTCTGTGAACTGTTTAGATAAGATCTTAACTGTCGGTGCTCGGAAAGGAATATCGACAGAATGTTTCGCCGTCGACAACTTTAGCTTGCCCTTGAACTTCGCGAAGTGGGTCCTCTGATGAACATTCGTGTCGCTAACCCTGTAATATAGTTTCCATGGGACTGGATCCTTCAGGGAGAAGAACGACGATGAGAAATAGTGGAGGTCGATGTTACACCGGATCGGGAATGTCCATGACGCCTGTAAGGATTCATTGTCCGTCATCCTCTTGTCGTGAATCTCCACGATGACGGAACCTGCGGCGTTTATGGGTACCTGCTGTCTGTATTCTATGACGCAATGGTCGATCTTCATACAGCTACGACTGAGCCTGGCGCTTATCTGAGCCGCCGCAGATGGAAACTGTAGTACGATCTCAGTTAGGTCGTGGGAAAGTTGATACTCATCACGCTGAGATTCTATATAATTAAAGGCATTTGGTGGATTAACTAACTGAGACTCCATTATTTAAGTTAAGAAGAATAGGCCGCGCAGCGGAATGTTTAGGCGAATTGGACAAGGTTATAATTGAAGGGGGAAGAAGACCTGAGTAAAATGAAAGAGTAAAGTGAAAGAGTAAAGTGAATAAGGTCGAAAGAAATGAGGGTTCCGGCAAGGTATAAATCCCGTGGACGGATTGAGAGGAGATATGAAAGAGGAAGTTGTTTTGCAATTTGTGCCTGATATGTCCTGTTTAAATAGACAGCGTCTGGAACGACTATTCATCGAATGGCATAAATGTAAATAAGACGGGGACTCCAACCCAGGACTCCAGGGGAGCTCTTAACTTCTGTCATATTTGCTGGAGTCCTGGAGTCCCATTTATACTACAACTCTCTAAGGCTCTTAGGGGGCACGTGGCGGCCATCCGTATAATATT",
        },
    ]

    assert result == sequences


@pytest.mark.asyncio
@pytest.mark.parametrize("isolates_to_compare ", ["source", "target", "both"])
async def test_compare_isolate(mocker, isolates_to_compare):
    mocker.patch("rich.prompt.Prompt.ask", return_value="Y")

    if isolates_to_compare == "source":
        isolates_to_compare = {
            "tandapi": [
                IsolateInfo(
                    ref="source",
                    otu_name="babaco_mosaic_virus",
                    id="ybkddtby",
                    sequences=[],
                    isolate={
                        "id": "ybkddtby",
                        "source_type": "isolate",
                        "source_name": "Tandapi",
                        "default": True,
                    },
                    taxid="2060511",
                )
            ]
        }
        expected = [
            {
                "ref": "source",
                "otu_name": "babaco_mosaic_virus",
                "id": "ybkddtby",
                "isolate": {
                    "id": "ybkddtby",
                    "source_type": "isolate",
                    "source_name": "Tandapi",
                    "default": True,
                },
                "sequences": [],
                "taxid": "2060511",
            }
        ]

    elif isolates_to_compare == "target":
        isolates_to_compare = {
            "tandapi": [
                IsolateInfo(
                    ref="target",
                    otu_name="babaco_mosaic_virus",
                    id="0f6",
                    sequences=[],
                    isolate={
                        "id": "0f6",
                        "source_type": "isolate",
                        "source_name": "Tandapi",
                        "default": True,
                    },
                    taxid="2060511",
                )
            ]
        }
        expected = [
            {
                "ref": "target",
                "otu_name": "babaco_mosaic_virus",
                "id": "0f6",
                "isolate": {
                    "id": "0f6",
                    "source_type": "isolate",
                    "source_name": "Tandapi",
                    "default": True,
                },
                "sequences": [],
                "taxid": "2060511",
            }
        ]

    else:
        isolates_to_compare = {
            "tandapi": [
                IsolateInfo(
                    ref="source",
                    otu_name="babaco_mosaic_virus",
                    id="ybkddtby",
                    sequences=[],
                    isolate={
                        "id": "ybkddtby",
                        "source_type": "isolate",
                        "source_name": "Tandapi",
                        "default": True,
                    },
                    taxid="2060511",
                ),
                IsolateInfo(
                    ref="target",
                    otu_name="babaco_mosaic_virus",
                    id="0f6",
                    sequences=[],
                    isolate={
                        "id": "0f6",
                        "source_type": "isolate",
                        "source_name": "Tandapi",
                        "default": True,
                    },
                    taxid="2060511",
                ),
            ]
        }
        expected = [
            {
                "ref": "target",
                "otu_name": "babaco_mosaic_virus",
                "id": "0f6",
                "isolate": {
                    "id": "0f6",
                    "source_type": "isolate",
                    "source_name": "Tandapi",
                    "default": True,
                },
                "sequences": [],
                "taxid": "2060511",
            }
        ]

    assert expected == await compare_isolates(isolates_to_compare)


@pytest.mark.parametrize("num_isolates", [1, 2])
def test_prepare_prompt(num_isolates):
    if num_isolates == 1:
        isolate_infos = [
            IsolateInfo(
                ref="source",
                otu_name="babaco_mosaic_virus",
                id="ybkddtby",
                sequences=[
                    {
                        "_id": "MF978248",
                        "accession": "MF978248",
                        "definition": "Babaco mosaic virus isolate Tandapi, complete genome.",
                        "host": "Vasconcellea x heilbornii",
                        "sequence": "GAAAAGCAAAGCAACTCAGCTCAACTCTCCACAAGAGAAATCAAAAGAAGTGCAAACCATTCGCGGCCCTCGAGGTGATCAATTACCCATCAAGGCTAGATCAACGGGATGGCTAACTTCAGAGCTGTTATGGACCAATTAAATGACCCCTCACTTAGAGCAGTAGTTCAAGAGGAGGCCTACAGAGAAATTAGGAAAACCATAGAAGTAACTAAAACATACAACCCATATGCACAGTCTTCGTTAGCAGCTGATTCATTAGAAAAATTAGGAATAGAAACTAACCCGCTCGCTGTAAGAGCTCACACTCACGCAGCAGCCAAATCAATAGAATTAGACATGTACAAAATAGCTTCCCATTATCTCCCGAAGGAGAATCCGGTAACGTTCCTCTTCATGAAAAGGGCTAAACTTCAATATTTCAGGAGAGGACCCCAACAGAACGACGTATTCTTAAATGCCCACGTTGAGCCCAAAGATGTGGTAAGATACGACCCGGACGATCTATTCGACGCAGACACAACACCCAAAATCCAAACGTCAGTAGCTTTCATGGGTGATGCTCTTCATTACTTCCCTCTAAGCGTGATCAACAAAATCTTCACAGCTTCCCCAAAACTCAAAACTTTGTACGCCACGTTGGTTTTACCAGCTGAGGCCGCTCACAGGATGCACTCATTACATCCAAGCATATATGAGCTCCAGTTCCACGAAGAGAATTTTTTGTACAAACCAGGAGGACACGCGGGTGCTGCATACTGCCACACATACAAGCAGCTTGAGTGGCTCCAAGTGGGAAGATTTCGATGGGAAACCGCCTCAGGCGAGGAAAGGAATGTCACTTCTCAAATACTGGAAACTAAAGGAGCAAACCACCTCATGGTCTTCCAGAGAGGATTGTACAACACACCGACCCTGAGGTGCTTCGGCGTCGAAACAAAATATGTGACCATGCCTCCCATTTTCCTACCAGCTAAATTCAACGCTCGACTGCCCATAAGAAAAACTGTCGCCCAACAACTCTTTCTCTACGTAAAATCTGTCAAGTCTGTGACCGAAAGAGATATATGGGCAAAAATCAGGCAACTCATCAAAACGGCTGACTTACAGGAATACTCCTCAAAGGAACTGACTTTGCTGGTAAACTATTTCTTTCTAATCTCAAAACTGAAGTCAGAAACATGCTTCGACAGCATCTTATCGGGGGGAATGATCAAGAGAGTGTTCAAACCTCTCATATCCTGGATCAATGAGAAGAAAGGTTTCATATTTGGAAAAGATCAGTTCATTCAGCTCATGGAAGCCTTGGAGTGGGTAGAAATCGACCTTACTTATAAGACAAAAACTTTCGATGAACCCAACGACAAATCAAGCTTCAACCCGATGGGATACCTGCCGTTGAAAGACGAGGAAGGCCTACCCGGGCTACAAGAGAGCAGCTCAGATCAACCTCAGGCTACCGAGGAGGATCAAGTGGCCTACGACAAATACCTCAAGGCACTAAGCAGGCTACAAGCGAGTGACGAGTCAGAGGAAAGAGAATCAGGCCCCCCCCCAAGCAATAGCGAGAGTGAGGCATCCAGTTCAGGAGGAAACCAAGCTGAAGAAACTAACAGCTGCCCACCAAACTCAACAGAAAAGAGCAGAGGTCTGGATGCAATACTGTGCCCATGTGGACTCTCAATACCCTTAGGAAAGGCAAAGTTTCCTGAAATTCCAGTTTTGGAACATCCCGAGAGACTCAAGGGAAGAGATGCCTTCTTCTTCTCAAAGGACAACAAGCCTTACTCCTACACAGGAGGGAGCCATCATTCAAGAGGCTGGCCATCTTGGCTAGACTCAATTCTGGCAGCAGTGGAAGTCCAGGAAACGATGCCAAATTTCAACCAATGCTTAGTCCAAAAGTTTTCCGCCAGAAGCTCAATCCCATTTCACAGGGATGATGAGAAGTGCTATCCCAAGGGGCACCAAGTCCTCACTGTAAACTTGAAAGGAACATGCACCTTCAAAATATGCTGTGACAGAGGGGTAGGAACAGCCAACCTGGAGGAAGGCACTTACCACTTATCCCCACCAGGCTTTCAGGAGAACCACAGGCATGCAGTGGAAGGGTGCTCAGCTGGCAGAGTTTCATTGACATTCAGATCAACTGCGATACAAGAACAACACTCTGAAGGCCTAGTCGCAGCCCCACTCGACTCACTTCCCTGGAAAGCATGGATACCAAAGCTCCAAGAATTAGGATTCCAGGGCAGACAACTGCAATATGATTGCAACGGTGCACTAATAAGCCCCATCGAACAGATCCAATCGATGGAAAAGACAAGGCCAAAGGGAGTTCCGGCTAGCCTTCTCACTTGCTTGGAAAAGATTGCTAGGGCACCAACCCACTTCTCCCCAAGTCCAATAAGAGCTAAAGCTTATTCCTCAGATGTGAAGAATGCGAGGATTGGAGCTATGCTGAAACAGCAAGGAAAGGATTGGGGGCACAGATTTGACGCGCTAGTCGAAGCTGGAAAGAGATCACTCCATATCTCGGTAATTCACGGAGCGGGTGGGTCAGGAAAGTCCCGCGCAATCCAAAACTACATTAAGGAGCACACAAAAGAGCCAGTCCAAGTAATCCTGCCCACCAATGAGCTAAGAATCGACTGGATGAGAAAAGTCCCGACCTTGAAGGAGACGATGTGCAAAACATTCGAGAAAGCACTGCTGGCTCCGCCCACACCAGTAGTCATATTTGATGACTACGGGAAGCTACCAGCAGGATACATAGAGGCCTTTTGCTTCTTCTTCTCCACTGTGGAGTTGGTCATACTAACTGGAGACTCAAAACAAAGCACACATCATGAGTCCAATGAGAACGCAATGACCAACCTGATCGAACCCTTCACATCGGAAGCTAGCAAACTGTGCAGATACTATGTGAACGCCACCCACAGAAACAAAAAAGATTTAGCCAACAAATTGGGCGTGTACTCAGAGGTTTCAGGCTTCACAGAAATTACGCACAGCTCCAGTCCAATTCCCGGGTTACACATCCTAGTGCCCTCTCTGTACAAAAAACAGGCTTTCTCAGAAATGGGACACAAAGCCTCCACCTATGCAGGGTGCCAAGGAATCACAGCACCCAAAGTCCAAATCCTGCTGTCTGAGGAGACAACTTTGTGCTCTAAAGAAGTGTTGTACACAGCACTGTCCAGGGCAGTGCACTCAATTCACTTCATCAACACTTCTCCCAACAACCAATCGTTCTGGAAAAAGCTGGAGAGCACCCCTTATCTGAAAGCCTTTCTCTCCACATTGAGAGAGGAAACAGCCCAAGAATCCAAACCAGCCCAAGGTGATCCGACTGCAGTTGATCCACCAAAGACACACATTCCAGTTGACTCAGCTCTGCCAATATACGAAAATATCTTGGATTCGATGCCAGAAAAACATGAAAGAGAGATATTTTCGAAGAGTCATGGGCACAGCAACTGCGTGCAAACAGAGGACTCATTTGTGCAGATGTTCTCACATCGGCAAGCAAAAGATGAAACCTTACTTTGGGCCACAATAGAAGCCAGACTTGTGGTCTCAAACCCCAAGTCGAATTGGCAAGAGTATCTAGAGAAGAAGCCAATAGGTGATGTACTCTTCGAGTCCTACAAGAAGGCTATGAAGTTGCCAGCTGAAAGAATTGCTTTTGAGCCTCAATTATGGGAATCGTGCATTCATGAAGTCCAAGGCACGTATCTGAAGAAAAGTGAGGACATGATCAAAAATGGTCAAGCTAGACAATCTCCCGATTACGACCCCAATCTCATATCGCTCTTCTTGAAGTCACAATGGGTGAAGAAAATGGAAAAATTGGGAGCGCTGAAAATAAAGCCAGGTCAGACCATAGCTTCTTTTCAACAAGCCACGGTCATGCTCTTCGGAACCATGGCTAGGTATATGAGAAGGATGAGGGAGGTCTTCATGCCAAAAAATATACTGATTAACTGCGAGACGACCCCAGAAAGCATGTCATCATGGGCTGCTGGAGAAGGAGGGTGCTGGAGCTTCAAAGGTCCCTCACTAGCCAATGACTTCACTGCGTTTGATCAATCCCAAGATGGAGCAATGCTGCAATTTGAGATATTGAAGGCCAAACATCACTCAATACCTGAGGATATCCTGGATGCCTACATCTCAATCAAAACCAATTCAAAAATCTTCTTGGGGACTCTAGCCATAATGCGTCTCACTGGAGAGGGTCCAACATTTGACGCAAACACGGAGTGCAACATAGCCTTCACCCACACAAAATTCCAAATACCAGATGGGACGGCTCAAATATATGCGGGAGATGACTCGGCAATTGATGCACTGCCCGTGGTGAGAAAAAGCTTCAAGCAAATTGAGAACAAGCTCACCCTAAAGTCAAAACCTCTGGTGGCCCTGCAACAGAAAGGAGACTGGGCTGAATTCTGTGGTTACAGGATAACTCCAGCAGGTTTCATCAAAGATCCAAAGAAATTGCACGCATCACTGATGTTAGAAGTTAAAAAGAAAAACATTAAAAATGTCAGAAGATCTTATGAGTTGGATCTAGCTCTTGCGTACCAACATAGAGACCGACTCCATGAACTGCTGTCTGAGGAGGAGCTGCGCTTTCATTACGAAACGGTTCGAACGCTGGTTAAGTCAGGAGGTGGGGAGGTTTTGAAAACATTCCTTCCCAAAGATGAATCACTTTATTGAAGTTCTCACAGCTCAGGGTTTCGTCAGGACTAACGAACCCATCAGTGAGCCACTAGTTGTCCATGCTGTTGCTGGCGCCGGGAAATCTTCCCTCGTGCGGCAATACATCTCCGAAAATCCAAACTCTAGAGCTTTCACACACGGCGTACCCGACCCACCCAACTTGACAGGTCGATTCATCCGCCCCTTCAGAGGCCCAATTGAGGGTTGCTTCAACATCCTGGACGAGTATTCGGCGGAGCCAATCGTTGGGAATTGGCAAGTTCTCATCGCCGACCCACTGCAACACAAGCCTCAAGCACTAACCCCCCATTACATCAAGGAGACCTCGCATAGACTAGGGAGCAACACTTGCGCCCTACTCACATCGCTGGGTATCAGGGTCAACTCCACCAGAACCGACGACTTCGTGGACTACTCCGGAATCTTCGACAAACCTTTGTTTGGAGAAGTCATTGCCTTAGACAGACCAACTTTGGATCTGTTGGAATCTCACGGCATATTACCGCACTGTGCGCAGAAAGTCTTGGGGCAGGAATTCCACACAACGACAGTCTTGAGCTCGGTACCACTGAACCTGGTCAGAGAGAAACACTTGCTCTACATTGCGCTGACCAGACACAAACACAAGCTCCATGTCAGAGCTCCCGCGCTCACTCACACCGCCAAGTGATAACTCTAGTGCTATATTAGCTGTAGCAGTAGGTATAGGATTAGCTTTGTTTACTTTCACACTACTCTCCTATAAACTGCCTGTACCCGGGGATAACATACATTCACTTCCCTTTGGAGGATATTATCGCGACGGAACTAAAAGCATATCCTACAACTCCCCAAGATCACAAGCCTCAGCTAGTAAAAGCGTCCCAGCCTTGCTAGTTTTGGCCTTAGTGGCTGCCATTTATGGCATCACTTGGGGAGATAAAAATCGCGCTCGCGGTGTTCGTGCTTGCCCTTGCCATCTTCACTCTCCTCAATAGCAATAAAAGGGAAACCTGCCTTGTGGAAGTCTCTGCAACTTTGTCACGAGTTTCCGGGCAGGACTGTAGGCACATCACCCCAGAAATAATTCAGGCTCTAGGAGAAGCGCTAGTCGGTCTTAGGTTGTAGAAGTAGTTGAAAATTTACTAATTTAAGCTGTTTTCTTAGTTATCTAGTTTTCAGGAGAAAATGAGTGGAAAGTCAGAGTCATCCAACACTGGAAACTCCCCCTTCCCAAATCTCACTAAAGAGACAATGGCCAGCTTCAACTTCAAACCAAGTTCAAACTTGCTACCTAGCGAGGAAGAGCTCAAGATCATATCCACATTACTGGTGGCAGCTAAAATACCCAACGCAAGCACCACCATTGTTGCAATGGACTTGGTCAACTTCTGTTATGACAATGGGTCTAGTGTGTACACGGTGATTTCTGGTGAATCCTCAATCACTGGCATCACTCTGGCCCAGATTGCAAGTATTGTCAAGGCTTCCGGCACTTCACTACGAAAATTCTGCCGATTCTTTGCACCAGTAATTTGGAACCTGAGGACTGACAAAGTACCCCCCGCAAACTGGGAGAGCGCTGGGTACAAACCAACTGAGAAATTCGCCGCCTTTGACTTCTTTGACGGCGTTGAGAACCCAGCAGCCATGCAACCACCGGGAGGGCTCATTAGGTCTCCAAATCAAGCGGAGAGGATAGCCAACCAAACTAACAAACAGGTGAACCTCTTCCAAACCGCAGCCCAGGGAAATAACTTGGCCTCCAACTCTGCATTCATAACCAAGGGGCAGATTTCAACGTCCACTCCATCTATCCAGTTTCTCCCATCCCCAGAGTAGGTTTGCCTCAATTGATGCAGGCATTCCTGGCACTGGCCACAATAAAGTGTGTGTTTATTTAAAAGAATCGAGCGTTCGCTTGATTCAATGCTGAAGTCCACCTAAAAGACTTCCTAGTTTGGCTTTAATATTAGTTTTCC",
                    }
                ],
                isolate={
                    "id": "ybkddtby",
                    "source_type": "isolate",
                    "source_name": "Tandapi",
                    "default": True,
                },
                taxid="2060511",
            )
        ]
        expected = (
            "Is this a new isolate?\n"
            "\n"
            "\t• Ⓢ  Source - Isolate Tandapi (2060511)\n"
            "\t\t• MF978248 | Babaco mosaic virus isolate Tandapi, complete genome. | Length=6692 | Hash=24910a29\n"
        )

    else:
        isolate_infos = [
            IsolateInfo(
                ref="source",
                otu_name="babaco_mosaic_virus",
                id="ybkddtby",
                sequences=[],
                isolate={
                    "id": "ybkddtby",
                    "source_type": "isolate",
                    "source_name": "Tandapi",
                    "default": True,
                },
                taxid="2060511",
            ),
            IsolateInfo(
                ref="target",
                otu_name="babaco_mosaic_virus",
                id="0f6",
                sequences=[],
                isolate={
                    "id": "0f6",
                    "source_type": "isolate",
                    "source_name": "Tandapi",
                    "default": True,
                },
                taxid="2060511",
            ),
        ]

        expected = (
            "Are these isolates the same?\n"
            "\n"
            "\t• Ⓢ  Source - Isolate Tandapi (2060511)\n"
            "\n"
            "\t• Ⓣ  Target - Isolate Tandapi (2060511)\n"
        )

    prompt = prepare_prompt(isolate_infos)
    assert prompt == expected


@pytest.mark.asyncio
async def test_write_isolates():
    verified_isolates = {
        "665102": {
            "otu_path": "tests/files/merged_ref/src/a/abutilon_brazil_virus",
            "isolate_infos": [
                {
                    "ref": "target",
                    "otu_name": "Abutilon Brazil virus",
                    "id": "un404hxp",
                    "isolate": {
                        "id": "un404hxp",
                        "source_type": "unknown",
                        "source_name": "unknown",
                        "default": True,
                    },
                    "sequences": [
                        {
                            "_id": "nm5iylku",
                            "accession": "NC_014139",
                            "definition": "Abutilon Brazil virus DNA B, complete genome",
                            "host": "Abutilon sp.",
                            "sequence": "ACCGGATGGCCGCGCGATTTTCCCCCCCCGCTCACGTGGCGCGCTCCTCTCCCTCCGATCTTCGTCCGCAACACGTGGCTTTGTGTTGCTCGCTCTATCCCGCTGGTCCCAATTTAGTTTAGCGCTATTTTGAAGTCCGCGAAATGAGCTGAGCGCATTTTTTGAGATCCGCCAACGGTATGCCGACATGTGGAATATTTGACTGCTTTGACTGTACTGGCGGACTTCTCTTTTTTATTTTTTGTGATTTATTTAAGACCGTTGGATAAAAATAAAAAATTTTGAAATTTGAATTATCGTGGCGCTGTCTGCCACTAAAGGAATATGGATGACCAATTATCTCTCGAGTTACAACCTTTAGGCATTGCGACGTGGCGCAATGAATTACCAATGGCTGAGGCAAAATAAGTTAGTATCGATTGGGAAATTTATGTATAAATTTCATCTGGATAAGTATTAGAAGATATAGTTTATACTTGGAAATAATTTCAAAATGTATTCGATCAAACACAAACGTGGTGTGTCTTCTACGTACCGGCGTAGTTATGCAAGGAATCCGTTATCCAAGCGTTCTTACGCCGTGAGACGCACCGATCGTAAACATCGGTCGAGTACTGTGAACAAGGCGCCGGAAGATGGTAAAATGACAGGTCAGCGTATGCACGAGAATCAGTTTGGGCCTGATTTTGTGATGGGCCATAATGCAGCCATATCCACGTATATCACCTACCCTGCTCTTGGTAAGAGTGAACCCAACAGGTCCAGGTCGTATATTAAGTTGAAACGTCTACGTTTCAAGGGTACTGTGAAGATAGAACGTGTACATGTGGATGTGAACATGGATGGAGTATCCCCGAAGATCGAAGGAGTATTTTCCATGGTCGTGGTCGTGGATCGTAAACCCCATTTGGGTCCGTCTGGATGTCTACCCACGTTTGATGAGTTATTCGGTGCAAGAATCCACAGCCATGGAAATTTGGCCATAACATCGTCCCTGAAAGACCGTTTCTATATTCGACATGTGCACAAACATGTGCTGTCGGTCGAGAAGGATAGCTTGATGGTAGACCTCGAAGGGACGAACTCTCTCTCTAGCAGGCGTTTTAACTGTTGGGCTAGCTTTAAGGACATTGACCGTGATTCATGTAACGGTGTTTATGCAAACATAAGCAAGAACGCCCTGTTAGTTTATTATTGTTGGATGTCGGACTCGTCGTCCAAGGCATCGACATTTGTATCGTTTGATCTGGATTATATTGGCTAAGAATAATAATTTATTTCAATACATGATAATGGCTTAGGATCTCGACAATTATGTTTATTATCTCAAAGACTTGGGCTCGGAGGGAGTGCAATTTGTGTTAATACACTCTTGGACCGTACTCCGAACAAGCTCGTTCAGTTGGGCCATTGACATGGTTATGTTGGACTGTGCCCTCTGGGCCCCGACAATTGAAGCAGAATCACCTGGGTCTAACATGGTGGTGCCCAACCTATGCAGCCCTCGATACGGGTGTGCTGCGATCTCCACCTCGGAGTCCGTTGTAGATTGACCGGTCCCTATGGTACTTCTGTGAGCCCAGGTCTCACCTGGATCAATTGATATTGGGCCTGGAAGCCCATGATTGACTGTTGATATGGATCGGATCAATTTCCTTTCCCATTTACCATAGCCCACATGGCAGAAGTCTATGTCTCTGTCTGTGAACTGTTTAGATAAGATCTTAACTGTCGGTGCTCGGAAAGGAATATCGACAGAATGTTTCGCCGTCGACAACTTTAGCTTGCCCTTGAACTTCGCGAAGTGGGTCCTCTGATGAACATTCGTGTCGCTAACCCTGTAATATAGTTTCCATGGGACTGGATCCTTCAGGGAGAAGAACGACGATGAGAAATAGTGGAGGTCGATGTTACACCGGATCGGGAATGTCCATGACGCCTGTAAGGATTCATTGTCCGTCATCCTCTTGTCGTGAATCTCCACGATGACGGAACCTGCGGCGTTTATGGGTACCTGCTGTCTGTATTCTATGACGCAATGGTCGATCTTCATACAGCTACGACTGAGCCTGGCGCTTATCTGAGCCGCCGCAGATGGAAACTGTAGTACGATCTCAGTTAGGTCGTGGGAAAGTTGATACTCATCACGCTGAGATTCTATATAATTAAAGGCATTTGGTGGATTAACTAACTGAGACTCCATTATTTAAGTTAAGAAGAATAGGCCGCGCAGCGGAATGTTTAGGCGAATTGGACAAGGTTATAATTGAAGGGGGAAGAAGACCTGAGTAAAATGAAAGAGTAAAGTGAAAGAGTAAAGTGAATAAGGTCGAAAGAAATGAGGGTTCCGGCAAGGTATAAATCCCGTGGACGGATTGAGAGGAGATATGAAAGAGGAAGTTGTTTTGCAATTTGTGCCTGATATGTCCTGTTTAAATAGACAGCGTCTGGAACGACTATTCATCGAATGGCATAAATGTAAATAAGACGGGGACTCCAACCCAGGACTCCAGGGGAGCTCTTAACTTCTGTCATATTTGCTGGAGTCCTGGAGTCCCATTTATACTACAACTCTCTAAGGCTCTTAGGGGGCACGTGGCGGCCATCCGTATAATATT",
                        },
                        {
                            "_id": "erdxaihh",
                            "accession": "NC_014138",
                            "definition": "Abutilon Brazil virus DNA A, complete genome",
                            "host": "Abutilon sp.",
                            "sequence": "ACCGGATGGCCGCGCGATTTTTTTAACCCCCCACGTGGCGCATTCCTGGTCGCGCGATCCCCCTCCCCCGCGCGCTTCTCTCCTTTAATTTTAATTAAAGTGCCTAACTTTCTACTGAGCCAATCATATTGCGCCTGACGAGTCTAGATATGTGGGAAAGACTTGGGCCCTAAGTTGTTGATTAACGGCTATAAATTAAAGGAAGACTGGTCACAGTCTTTAATTCAAGATGCCTAAGCGGGATGCCCCTTGGCGCCTTATGGCGGGAACTTCGAAGATTAGCCGTTCCTCTAATACCGGCCCTCGTGGAGGTTCTGGGCCTAAATTCAATAAGGCCAATGAGTGGGTCAACAGGCCAATGTACAGGAAGCCCAGGATATACCGGGCCTTCAGAACTCCAGATGTCCCTCGAGGGTGTGAAGGGCCTTGCAAGGTCCAGTCGTACGAACAGCGACACGACATCTCACATGTCGGCAAGGTCATGTGTATATCTGATATCACCCGAGGTAACGGTATTACTCACCGTGTGGGTAAGCGCTTCTGTGTTAAGTCTGTGTATATTTTAGGTAAGGTATGGATGGACGAGAATATCAAGCTCAAGAACCACACGAACAGTTGCATGTTCTGGCTAGTCAGGGACCGTAGACCGTATGGTACACCCATGGACTTTGGCCAGGTGTTCAACATGTTCGACAACGAGCCCAGTACTGCAACCGTGAAGAACGATCTCCGCGATCGTTTCCAGGTCATGCACAAGTTCTATGCCAAGGTTACTGGTGGTCAGTATGCCAGCAACGAGCAGGCTCTGGTCAAGAGATTCTGGAAGGTCAACAATCATGTGGTCTACAATCACCAAGAGGCCGGGAAGTACGAGAATCATACGGAGAACGCACTATTACTGTATATGGCATGTACCCATGCCTCTAACCCCGTGTATGCAACGCTCAAGATTCGGATCTATTTTTATGATTCGATCACAAATTAATAAAATTTGAATTTTATTGAATGATTTTCCAGTACATGATTGACATACGACTTGTCTGTTGCGAAACGAACAGCTCTAATTACATTATTAAGCGCAATTACACCTAATTGCTCTAAGTACAGCATGACTAAGTGCTTAAATCTAGCTAAATAAGTCTTCCCAGAAGCTGTCAGAGAAGTCGTCCAGACTTGGAAGTTCAGGAATGCCTTGTGGAGACCCAATGCTCTCCTGAGGTTGTGGTTGAACCTTATCTGGATGTGGTACACTCTTGTCCGAGTGTACGGTGGATCCTCTACCCTGTACATCTTGAAATACAGGGGATTTGTTATCTCCCAGATATAGACGCCATTCTCTACCTGACGTGCAGTGATGAGTTCCCCTGTGCGTGAATCCATGGCCTGTGCAGTTGAGATGCTGGTAAATGGAGCAGCCGCAGTCCAGATCAATTCGTCGTCGTCTGATTGCTCTCTTCTTCGCAATCCTGTGTCGTGGTTTGATAGAGGGGGGAGTTGAGGAAGATGAATTTAGCATTGTGTATTGTCCAGGCTTTTAGTGATGAGTTTTCCTGCTTGTCCAGGAAATCTTTATAGCTGGCCCCCTCTCCAGGATTGCAGAGCACGATTGATGGGATACCCCCTTTAATTTGAACAGGCTTGCCGTACTTGCAATTGGACTGCCAATCTTTTTGAGCACCAATCAATTCCTTCCAGTGCTTTAGCTTTAGGTATTGCGGGCTGACATCATCGATGACGTTATACTCAACTTGATTTGAGTAGACCCGGGAATTGAAATCTAAATGGCCACTCAAGTAATTATGTGGGCCTAACGCACGAGCCCACATCGTCTTACCAGTTCGAGAATCACCTTCTACAATCAAACTGATGGGCCTGATAGGCCGCGCAGCGGAACCTCTCCCAAAATAATCATCCGCCCATTCCTGCATCTCTTCCGGAACGTTAGTGAACGATGAGAGGGGAAACGGTGGAGCCCACGGTTCCGGAGCCTTTGTAAAGATCTTTTCTAGGTTGGAGCGGATGTTATGGTGTTGGACGATGAATGACTTTGGATCTCCGGCTCTGATAATTTCAAGAGCCTCTGAAACACCTCCTGCATTGACGGCGTTGTGGAAGACATCGTCCTTGTTGGCCTTGGTACCCCCAGACACTTTGTATTGTCCGGATTCACAATAGTCACCATCTTTGGTGATGTAGTTCCTGACGGCAACGGTGTCTTTGGCAGCTTGCACGTTTGGGTGAAAACTGGCTGACCGTCTGGGGTGAGTAAAGTCGAAAAATCTTGCATCCTTGATGTTGGACTTCCCTGATAATTGTATGAGACAGTGTAGATGGGGGTTTCCATCGGAGTGTTCCTCACGTGCGACTCTGATATAGGTAGGTTGGACGACTGCCCATGGAAGGGCTTGAAGCATTTGAAGAGCTTCATCTTTGGGTATGTCGCATCGCGGATATGTGAGGAATATGTTTCTGGCTTGTAATCTAAAAGAATGGGGAAGTCGGGGCATATTTGTAAATTTATGTTCAGGACTCCAGCCCAGGACTCCAGGGGAGCTCTCAACTTCTGTCATATTTGCTGGAGTCCTGGAGTCCCATTTATACTACAACTCTCTAAGGCTCTTAGGGGGCACGTGGCGGCCATCCGTATAATATT",
                        },
                    ],
                    "taxid": "665102",
                }
            ],
        },
        "190811": {
            "otu_path": "tests/files/merged_ref/src/b/bamboo_mosaic_virus_satellite_rna",
            "isolate_infos": [
                {
                    "ref": "target",
                    "otu_name": "Bamboo mosaic virus satellite RNA",
                    "id": "ae7vj1om",
                    "isolate": {
                        "id": "ae7vj1om",
                        "source_type": "unknown",
                        "source_name": "unknown",
                        "default": True,
                    },
                    "sequences": [
                        {
                            "_id": "d2zm58z1",
                            "accession": "NC_003497",
                            "definition": "Bamboo mosaic virus satellite RNA, complete genome",
                            "host": None,
                            "sequence": "GAAAACTCACCGCAACGAAACGAAACAAATCGTTCAGAAACACTAGACCACGAGGGCCCCCCTATAGTCCCGCTGAGGGTGTGGCAGGCCCCGTGCGATAGGCTAACTGTGGTGTTCCCCGCACTCCGTCGAGCGGTTAATACGACGCTTACCAAGACGATGGTTCGGAGGAGAAATCGTCGCCAGAGATCGCGTGTCTCCCAAATGACCGACATCATGTATGGCTCACTAACACTGGGCAGTACCACAACATGGACCAGGAAGAATTTCCCTGGGTTGGCCAATATGGGAGATCGACCTTTCCAGGTCATCTCTGTTAAAATTGTTGTCTCGTCTGCCTCCCCCATGCTTTACCAAGCCAGGCTTTACTCACCACACGATGATGACAATGTGGGGTCCACCGGGCTTCAAATGTCTGGAACCACTCCACACACTCACCATATGAGAGCTCTGCCAGGTCAAAACACCTGGTTTAGTGGCAACACGAGCTCTACTCAGGTGATTGTCGCCATTGATGGCCTGAAGACGAAGACAACGGATGCCACGCCCCAGAACGCGGTGGCCGTTCAGGTGTTCTATCGAGTGGCGCCGAGCGAACTCCAGAGCGCAACTGGTAATGCTGAAATGCCTACAACCACGCCTTTTGACCTCCCAGAGGGGTATGAATACCTCGCTGACGCGTGGCTCCCTGACCGTGCACCAACCAGTTGATCCACGAGCACAACCGGCTTGTCAATGAGCCGCCAGGTTTAGCCTGGTTCCACATTGACCCACCACCCATACTATGAGACCTAACCAGTAGTGGTGGTCGTCCCGAATAAAGACGCTAAAAGATG",
                        }
                    ],
                    "taxid": "190811",
                }
            ],
        },
        "35286": {
            "otu_path": "tests/files/merged_ref/src/b/bamboo_mosaic_virus",
            "isolate_infos": [
                {
                    "ref": "target",
                    "otu_name": "Bamboo mosaic virus",
                    "id": "lm3xmhrf",
                    "isolate": {
                        "id": "lm3xmhrf",
                        "source_type": "isolate",
                        "source_name": "BaMV-O",
                        "default": True,
                    },
                    "sequences": [
                        {
                            "_id": "3d2e72sk",
                            "accession": "NC_001642",
                            "definition": "Bamboo mosaic virus, complete genome",
                            "host": None,
                            "sequence": "GAAAACCACTCCAAACGAAACGAAAAGAAAAGAAAAGACGAAAGAAAACGAAACTGCCAATTGTCCCCTACAATGCCCTGCGCGTGCGGCAACAATGGCACTCGTTTCTAAAGTCTTTGACAGCATCACCGACCCATCCTTGAGGGCTGTACTCCAAGAGGAAGCGCACTCCCAAGTTAAACAAGTGCTCAAAGACACAGCGCTCTACTCCAGATACGCCCTCCTCCCCACTGCTGCAAACACGCTTGAACGGTACGCAATCCCTCATAACCCGTTCAGCACAAAATTACACACACACGCAGCAGCAAAAGCCCTTGAGAATGACCTCTACCGGACGGCCTCATATCTCCTCCCAAAAGAAAGAGTGTCATTTCTTTTTATGAAGCCATCTAAGATGCAATATTTCCGGAGAAGAGGAGATGTCGACACCTTCATCAATGCTGACATCGTTGCTAAAGACCTTGCCAGGTACCCTCTCGAGACTATCTACCCCCGCCTCCCGGAAATCACAACAAAGATGGCTTTTATTGGGGACAGCCTGCATTACTTCCAGCCTGAGGTGCTGGAGCACATTTTCACAAGCTCCCCACAACTAGAGACCCTGCTCGCCACGATCGTCCTTCCCCCCGAAGCCACACTCAGGCTTAAAAGTCTATACCCAGAAATCTACACGTTGCACTACATGCCCCAAAAATTTCTCTACAAACCTGGGGGCCTATCAGGCGGGGAATACGAACATGATTACAAGGACCTAACTTGGCTGAAGATTGGGCATGTCACAACTGCTTCCATGTGCCTCACAGTCGACCGGGTGGAGTCTAAAGCGGCCAATCACTTACTACTCATACGGCGTGGAAGGCTCAAACTCAGCACTTACAGATCTTACGACACCCCTGAGCCCTTAGTCGTGGTACCAAAAATATTCCTCCCCCCAAAGTATAATGCACAGAAACCAATTACTAAGACGAAAGCAAACTCGTGGATTCTCTACGTTAAATCAGCTGGGGAGCCGAAGATTAGGGATGTTTGGGCCAAGCTCAGGCAGACGATAGCGAACTCTGAACTCAACCAATACGAGCCTGCGGAATTGCTGCTACTAACCAACTACTTCTACGTGTTGGGCAAGTTGGACTCCATCACGTCCTTCGAAACTCTTCTCGGGGACAATATACTCAAGCGCCTTTTCAGACCGGCGATAGCAAAAATCCAAGAACTCAGACACTGGGTTAGTGGCCCAACAGCCTTCATGCAACTCTACAAAGCGCTGCAACTCGTCGATGTAGACTTCACTTTTGAGGTCACTAAGAACTGGGAAACAAAACAGGAGAACCACAGCGAACCCGAACTCCCAAAAGATGCCATTGACGTGCTCGTCCAGTCGCTCATCGGCATCAATTACACAGACGCAGCAACTACCGAAGCCGCAAACCCTAAACAACAAGAAAGTGGACCAAAACCCTACACCAACCTCCCGCAGCCCCTTCAGCAAACCAAATGCCCCGAGGACACGGAAGTGTCCGCATCACCAGAATGCAAAGCGGCTGAAACTGCGCAAGAGACCCACAAAGCAGGGCCCAGTTCAAACCCCGCTCTCAACACTGACCAAGAGGCAGCCCCGTCAGAACCCACAGACAGCGAGGAGCGGAAGTGCCCCACATTGCGTGAACTGCCATGGAAGGCGTGGCTCAAACTACTTCGGGGCCTTGGATTCCAAGGCGACCTTGAACAGTTGGACGTAGAGGGGGACCTCATTTACCCAATTAAACACATCCGGCACTTACCAGTTGAGGATTTCAGTGGCCCGATCACAGCGACCCTGAGGAAAATGAACCGGATGCCATGCAAATACTCCCCCGACATTGAAAGAGCAGCCGCATTCGCGCGAGACGTGATGAGCAATAAAACAGGGGCCATCCTCCCCAAACAATCCCACGAATGGAAGACCACACTTAAAAGAAAATGCAAACTTGCCCCTCGACAAACTCTTATTTCCGTGATACATGGCGCGGGCGGCAGTGGTAAATCAAGAGCCCTGCAAGAATACATGAGGAACAACAAGGAGGACCCCATCGTCACCATCCTTCCGACGAATGAGCTAAGGGCCGATTGGAAAGCTAAACTGCCCGCTCATGACCCTGACATGTTCATGACATTCGAGAACGCGCTGCTGATCCCAAAAGGCAACGTAGTCATCATGGACGATTACACTAAGCTACCACGCGGGTACATCGAGGCGTACGTGCAAAACTCCCCAATGCTAGACCTGCTCATACTCACAGGAGACCCCAGGCAATCCGAACACTTCGAATCAGCCGAAGGGAACACGATCAACGATCTCAGCCCCTCTCCAGTCGTCTTCAGCGCGTACGCCCGCTATTACATCAACGCAACTCACAGGAACAACCAGGACCTAGCGAACGCCTTGGGGGTTTACTCTGAAAAACAAGGGAAAACGCGAATATCAGTCAGTAACCATATAGAAGACGGGCGCCACACATTAGTTCCCAGCCAAATCAAACAAAGAAACTACGTCTCCATGGGCAGGAAAACTTCTACCTATGCGGGCTGTCAAGGGATAACCGCTTCACGTGTACAGGTCATCATTGACAACGACACTGCAAAGTGCTCACATCAGGTCCTATACACAGCTTTTTCCAGGGCCGCAGACGAAATACACTTCTGCAACACTATGACCGACGAAAAACAATTTTGGGCGAAAGTGAAGTGTACCCCGTACTTACAAGCCATCCTCAACCTTACAAAGGAACACTCTCTGCCTGACCCGAAGCCTGAGCCAGATGAACCCTTGGAGCCCAAAGCCCCTGTCACCCACATTGCTGTGGAAAACGTGGTACCGCTAGTGGAAGAAATCACTGAGCCTCTTCCAGAGAAGCATGACCGAGAGATCTACTCAGAAAGCACCGGACACTCCAACTGCATCCAAACCGAAAACGAGTTCATTCAGGCTTTCCAACACCAACAGGCAAAGGATGAAACTCTCTTCTGGGCCACCATTGAGAAACGCATAGTCACCTCAACCCCTGAATCAAACTGGACTGAATTCAAGACAAAGAGGCCCCTAGGTGACATCTTGTGGCTGGCCTACAAGGAGGCTATGTGCTTGCCAGCGGAGCCCATCAAATTCGACCCAGACCTTTGGTGGAAATGTGCCGATGAGGTGCAAAATAAATACCTACAAAAACCCCTTCACATGATCAAAAACGGAATACTCAGACAAAGCCCAGACTTTGGGGAGCGTCACATCGCGCTATTTCTAAAGTCGCAGTGGGTAAAGAAAAACGAAAAAATTGGGACAGTCAACGTTAAGGCTGGTCAAACTATCGCCGCGTTCTACCAGAGTACTGTCATGATCTTCGGCACGATGGCGCGCTACATGCGGCGTGTAAGAGAAAAATTCTGCCCAAAGAACATACTAATTAACTGCGAAATTGACCAGCCCACAGCTTCAAAATGGGTGGACACGCATTGGAAATTCGACAGGTTGGCATACACAAACGACTTTGAGGCGTATGACCAGTCTCAAGATGGGGCCATGTTGCAATTTGAGGTGATGAAAGCAAGGCACCATGATCTGCCTGCTGATTTGATCGAGTCCTACATCGAACTTAAGCTGAACGCCAAAATATTCCTAGGCACCCTTGGCATCATGAGACTCACTGGAGAGGGGCCAACCTTCGATGCCAATACTGAATGCAACATCGCCTACACGCATGCCCGATTCCACATACCCAGAGGCACTGCACAACTGTACGCTGGAGACGATTGCGCCCTCAACTGCGAACCTGAAGAGAGAGAATCATTTAAACCTTTAGCTGCGCAGTTCACCCTCAAATCAAAGCCGGTGACCATAAGACAAGGAAAAGGCTCCTGGCCCGAGTTCTGTGGCAATATCATCACCCCTTACGGCTACCTCAAACATCCTCGGAAAACATGGGCTGCACTGCACAAGGCCAAACTTCAAGGGAAAGATGAATTGAAGAAAACCGCCACGGCCTATGCGCTCGACGTGCTACCAACGTACGAACTAGGGGACGCAATACACGATATATTTACCGACAACGAGCTGACATTCCACTACCAAACAATCAGAACCCTACACACAGAAGCCCACACTCGAGTCTTCGCCAACCACGATGCAATCTTTGGCGAAGAAGGTTTATTCTCTAGTTAAGTAACCTATTAGTTTAACAACTAACCATGGATAACCGGATAACTGACCTACTCACAAGATCTGGCTACTTAAGAACATCAGAACCAAGAGGCGCCGGGCAGCAACTGGTCGTGCACGCGGTGGCTGGCGCTGGCAAGACAACGCTACTCCGCGAGATACTAAATACCATTCCAGGAGTCACCATACACACTGCAGGCACCCCCGACCCACCAAACCTCACACTCAACTACATCAAAGGCCAAGAGCCCCCTTGCCCGAAGAAGTACACTATCCTAGATGAGTACCCAGCTAGAGCCAAGTGGCCGGAGGAGGCCTGGGACATGTTGATTGCTGACAACCTCCAACACACAGGCCCCACGACCCGCCCCCACTATATAAAACACACCACCTACAGACTTGGTCCCCAAACAGTCAAAACGTTGCAAAGCCTTGGGTACCAACTGGAATTCCAACATCGGGCAGACCAGCAAGACCAGGGCTTCTCATTCACCGGACTATTCGACGGCCCAATTTACGGACAACCGATCACACTCGACACAGCAGCCCACAACCTGGCACTAGCTCACGGACTACCAGCTCTACAAGCAACTCAAACGAGAGGGCTAGAATACGACACCACTACCATCATCTCTAGCACTCCTCTGCCAACAGTTAAGGACAAGGTGGGCCTATACATTGCTTTCACCAGGCACCGAAAAGCCTGCCATATTCGAGCACCTGGGATCAACCCCACATGTGACGTGGCCTCCTCTCATGGACCAGCCTCTTCATCTGGCCAGACCACTTGACAACACGAGAGCTTACTTAGTATTAGCTATAGGAGTAGCGAGTGCATTGTTCCTCTATACACTAACCCGTAATACCCTTCCACACACCGGCGACAACATCCACCATTTACCGCACGGGGGTAGGTACGTGGACGGCACCAAAGGAATTCTCTACAACAGCCCCACCTCCTCATACCCATCCTCATCTCTCCCATTCTCCATGGTTATCGCACTAGCCACAACCCTTTTCCTCATCACCAGAAACATTCTCAACCCAGCCCCCACCACACCTAGAATCTATGCGCCCCTCTGCTTGCATTGTCACCGGAATCACCCACCATGCTAAACACTGACACACTATGCATCATTCTGTTCATACTAATATTAGGCATCCTATATAATATACTTCAACAGCATCTGCCCCCACCATGTGAAATAATAATAAACGGGCACACTATATCCATTAGGGGCAACTGCTACCACACCACCTCCAGCTAGGGTTTGTTAAGTTTCCCTTTTTGTAAATTAAACACTAAAGATGTCTGGAACTGGAACGGGAACTGGGCGAGGGACCGGGACAGGAGTAGGAGGCACTGGAGGCACAGGTGGCACAGGCGGCGGAGGAACAGGTAGAGGGCAACAAGCTGCACCCCAGCCCTGGGAAACAAAGTTCACTAAGGACGACCTGGCCGCAATCGAGCCAAAACCTGCTTCGGCAAATGTTCCAAACACTAAGCAGTGGATCAGCATTCAAGCTGGACTCATCAAGGCTGGAGCCACGGACGCAAACTTCATGAAAGTACTGCTCGGCCTCAGTCTCGAAGCTTTCGACAGGGGCTCGTCGGAGGCCACCACTTGGGATGGAATTACTGAGGGCGTGGAGCACCGTGCAGCAGCCAACGCCATCAAGGAGGCGAACTGCCCAATACACAAGGTCACCTACTACCTAGCCAAACCGACGTTCGCCATTAGACAATCGAAAAACCTCCCCCCAGCGAACTTCGCGAAGAAGAATGTGCCATCACAATATAAATGGTGTGCGTTCGATGCTTTTGATGGCCTGTACGATCCCACCTGCCTTGCCTCAGAACTACCCTACGACGCCCCCTCAGAAATAGACCGAATGGCGTCCGCTACCTTCAAAACTATACAGATCAAGATCGCTAATGACCAGAAAGGGTTCAACCTCAACTACAACCCTAACGTCACCCAGGCTCGACTCCCCAACGCGCCCCTACCAGCTCTTCCCGAACCAACATCAGACTAAACGTTGCATGATCGTAAAACATGCCCGGCTTACCGTGAGCCGCCTTTGAAAGAAAGGTTTACACGGACTCTGTTGCGTTACGCACGTACCTAACCCGTGCCAGCAGAATAAAGACCTTTTGGTTTCTACAGTTTTTTCCA",
                        }
                    ],
                    "taxid": "35286",
                }
            ],
        },
    }

    await write_isolates(verified_isolates)

    for _, result in verified_isolates.items():
        for isolate_info in result["isolate_infos"]:
            isolate_info = IsolateInfo(**isolate_info)
            isolate_path = Path(result["otu_path"]) / isolate_info.id / "isolate.json"
            with open(isolate_path, "r") as f:
                assert json.load(f) == isolate_info.isolate


@pytest.mark.asyncio
async def test_write_sequences():
    isolate_path = Path("tests/files/merged_ref/src/b/bamboo_mosaic_virus/lm3xmhrf")
    sequence_path = Path(
        "tests/files/merged_ref/src/b/bamboo_mosaic_virus/lm3xmhrf/3d2e72sk.json"
    )

    isolate_path.mkdir(parents=True, exist_ok=True)

    sequences = [
        {
            "_id": "3d2e72sk",
            "accession": "NC_001642",
            "definition": "Bamboo mosaic virus, complete genome",
            "host": None,
            "sequence": "GAAAACCACTCCAAACGAAACGAAAAGAAAAGAAAAGACGAAAGAAAACGAAACTGCCAATTGTCCCCTACAATGCCCTGCGCGTGCGGCAACAATGGCACTCGTTTCTAAAGTCTTTGACAGCATCACCGACCCATCCTTGAGGGCTGTACTCCAAGAGGAAGCGCACTCCCAAGTTAAACAAGTGCTCAAAGACACAGCGCTCTACTCCAGATACGCCCTCCTCCCCACTGCTGCAAACACGCTTGAACGGTACGCAATCCCTCATAACCCGTTCAGCACAAAATTACACACACACGCAGCAGCAAAAGCCCTTGAGAATGACCTCTACCGGACGGCCTCATATCTCCTCCCAAAAGAAAGAGTGTCATTTCTTTTTATGAAGCCATCTAAGATGCAATATTTCCGGAGAAGAGGAGATGTCGACACCTTCATCAATGCTGACATCGTTGCTAAAGACCTTGCCAGGTACCCTCTCGAGACTATCTACCCCCGCCTCCCGGAAATCACAACAAAGATGGCTTTTATTGGGGACAGCCTGCATTACTTCCAGCCTGAGGTGCTGGAGCACATTTTCACAAGCTCCCCACAACTAGAGACCCTGCTCGCCACGATCGTCCTTCCCCCCGAAGCCACACTCAGGCTTAAAAGTCTATACCCAGAAATCTACACGTTGCACTACATGCCCCAAAAATTTCTCTACAAACCTGGGGGCCTATCAGGCGGGGAATACGAACATGATTACAAGGACCTAACTTGGCTGAAGATTGGGCATGTCACAACTGCTTCCATGTGCCTCACAGTCGACCGGGTGGAGTCTAAAGCGGCCAATCACTTACTACTCATACGGCGTGGAAGGCTCAAACTCAGCACTTACAGATCTTACGACACCCCTGAGCCCTTAGTCGTGGTACCAAAAATATTCCTCCCCCCAAAGTATAATGCACAGAAACCAATTACTAAGACGAAAGCAAACTCGTGGATTCTCTACGTTAAATCAGCTGGGGAGCCGAAGATTAGGGATGTTTGGGCCAAGCTCAGGCAGACGATAGCGAACTCTGAACTCAACCAATACGAGCCTGCGGAATTGCTGCTACTAACCAACTACTTCTACGTGTTGGGCAAGTTGGACTCCATCACGTCCTTCGAAACTCTTCTCGGGGACAATATACTCAAGCGCCTTTTCAGACCGGCGATAGCAAAAATCCAAGAACTCAGACACTGGGTTAGTGGCCCAACAGCCTTCATGCAACTCTACAAAGCGCTGCAACTCGTCGATGTAGACTTCACTTTTGAGGTCACTAAGAACTGGGAAACAAAACAGGAGAACCACAGCGAACCCGAACTCCCAAAAGATGCCATTGACGTGCTCGTCCAGTCGCTCATCGGCATCAATTACACAGACGCAGCAACTACCGAAGCCGCAAACCCTAAACAACAAGAAAGTGGACCAAAACCCTACACCAACCTCCCGCAGCCCCTTCAGCAAACCAAATGCCCCGAGGACACGGAAGTGTCCGCATCACCAGAATGCAAAGCGGCTGAAACTGCGCAAGAGACCCACAAAGCAGGGCCCAGTTCAAACCCCGCTCTCAACACTGACCAAGAGGCAGCCCCGTCAGAACCCACAGACAGCGAGGAGCGGAAGTGCCCCACATTGCGTGAACTGCCATGGAAGGCGTGGCTCAAACTACTTCGGGGCCTTGGATTCCAAGGCGACCTTGAACAGTTGGACGTAGAGGGGGACCTCATTTACCCAATTAAACACATCCGGCACTTACCAGTTGAGGATTTCAGTGGCCCGATCACAGCGACCCTGAGGAAAATGAACCGGATGCCATGCAAATACTCCCCCGACATTGAAAGAGCAGCCGCATTCGCGCGAGACGTGATGAGCAATAAAACAGGGGCCATCCTCCCCAAACAATCCCACGAATGGAAGACCACACTTAAAAGAAAATGCAAACTTGCCCCTCGACAAACTCTTATTTCCGTGATACATGGCGCGGGCGGCAGTGGTAAATCAAGAGCCCTGCAAGAATACATGAGGAACAACAAGGAGGACCCCATCGTCACCATCCTTCCGACGAATGAGCTAAGGGCCGATTGGAAAGCTAAACTGCCCGCTCATGACCCTGACATGTTCATGACATTCGAGAACGCGCTGCTGATCCCAAAAGGCAACGTAGTCATCATGGACGATTACACTAAGCTACCACGCGGGTACATCGAGGCGTACGTGCAAAACTCCCCAATGCTAGACCTGCTCATACTCACAGGAGACCCCAGGCAATCCGAACACTTCGAATCAGCCGAAGGGAACACGATCAACGATCTCAGCCCCTCTCCAGTCGTCTTCAGCGCGTACGCCCGCTATTACATCAACGCAACTCACAGGAACAACCAGGACCTAGCGAACGCCTTGGGGGTTTACTCTGAAAAACAAGGGAAAACGCGAATATCAGTCAGTAACCATATAGAAGACGGGCGCCACACATTAGTTCCCAGCCAAATCAAACAAAGAAACTACGTCTCCATGGGCAGGAAAACTTCTACCTATGCGGGCTGTCAAGGGATAACCGCTTCACGTGTACAGGTCATCATTGACAACGACACTGCAAAGTGCTCACATCAGGTCCTATACACAGCTTTTTCCAGGGCCGCAGACGAAATACACTTCTGCAACACTATGACCGACGAAAAACAATTTTGGGCGAAAGTGAAGTGTACCCCGTACTTACAAGCCATCCTCAACCTTACAAAGGAACACTCTCTGCCTGACCCGAAGCCTGAGCCAGATGAACCCTTGGAGCCCAAAGCCCCTGTCACCCACATTGCTGTGGAAAACGTGGTACCGCTAGTGGAAGAAATCACTGAGCCTCTTCCAGAGAAGCATGACCGAGAGATCTACTCAGAAAGCACCGGACACTCCAACTGCATCCAAACCGAAAACGAGTTCATTCAGGCTTTCCAACACCAACAGGCAAAGGATGAAACTCTCTTCTGGGCCACCATTGAGAAACGCATAGTCACCTCAACCCCTGAATCAAACTGGACTGAATTCAAGACAAAGAGGCCCCTAGGTGACATCTTGTGGCTGGCCTACAAGGAGGCTATGTGCTTGCCAGCGGAGCCCATCAAATTCGACCCAGACCTTTGGTGGAAATGTGCCGATGAGGTGCAAAATAAATACCTACAAAAACCCCTTCACATGATCAAAAACGGAATACTCAGACAAAGCCCAGACTTTGGGGAGCGTCACATCGCGCTATTTCTAAAGTCGCAGTGGGTAAAGAAAAACGAAAAAATTGGGACAGTCAACGTTAAGGCTGGTCAAACTATCGCCGCGTTCTACCAGAGTACTGTCATGATCTTCGGCACGATGGCGCGCTACATGCGGCGTGTAAGAGAAAAATTCTGCCCAAAGAACATACTAATTAACTGCGAAATTGACCAGCCCACAGCTTCAAAATGGGTGGACACGCATTGGAAATTCGACAGGTTGGCATACACAAACGACTTTGAGGCGTATGACCAGTCTCAAGATGGGGCCATGTTGCAATTTGAGGTGATGAAAGCAAGGCACCATGATCTGCCTGCTGATTTGATCGAGTCCTACATCGAACTTAAGCTGAACGCCAAAATATTCCTAGGCACCCTTGGCATCATGAGACTCACTGGAGAGGGGCCAACCTTCGATGCCAATACTGAATGCAACATCGCCTACACGCATGCCCGATTCCACATACCCAGAGGCACTGCACAACTGTACGCTGGAGACGATTGCGCCCTCAACTGCGAACCTGAAGAGAGAGAATCATTTAAACCTTTAGCTGCGCAGTTCACCCTCAAATCAAAGCCGGTGACCATAAGACAAGGAAAAGGCTCCTGGCCCGAGTTCTGTGGCAATATCATCACCCCTTACGGCTACCTCAAACATCCTCGGAAAACATGGGCTGCACTGCACAAGGCCAAACTTCAAGGGAAAGATGAATTGAAGAAAACCGCCACGGCCTATGCGCTCGACGTGCTACCAACGTACGAACTAGGGGACGCAATACACGATATATTTACCGACAACGAGCTGACATTCCACTACCAAACAATCAGAACCCTACACACAGAAGCCCACACTCGAGTCTTCGCCAACCACGATGCAATCTTTGGCGAAGAAGGTTTATTCTCTAGTTAAGTAACCTATTAGTTTAACAACTAACCATGGATAACCGGATAACTGACCTACTCACAAGATCTGGCTACTTAAGAACATCAGAACCAAGAGGCGCCGGGCAGCAACTGGTCGTGCACGCGGTGGCTGGCGCTGGCAAGACAACGCTACTCCGCGAGATACTAAATACCATTCCAGGAGTCACCATACACACTGCAGGCACCCCCGACCCACCAAACCTCACACTCAACTACATCAAAGGCCAAGAGCCCCCTTGCCCGAAGAAGTACACTATCCTAGATGAGTACCCAGCTAGAGCCAAGTGGCCGGAGGAGGCCTGGGACATGTTGATTGCTGACAACCTCCAACACACAGGCCCCACGACCCGCCCCCACTATATAAAACACACCACCTACAGACTTGGTCCCCAAACAGTCAAAACGTTGCAAAGCCTTGGGTACCAACTGGAATTCCAACATCGGGCAGACCAGCAAGACCAGGGCTTCTCATTCACCGGACTATTCGACGGCCCAATTTACGGACAACCGATCACACTCGACACAGCAGCCCACAACCTGGCACTAGCTCACGGACTACCAGCTCTACAAGCAACTCAAACGAGAGGGCTAGAATACGACACCACTACCATCATCTCTAGCACTCCTCTGCCAACAGTTAAGGACAAGGTGGGCCTATACATTGCTTTCACCAGGCACCGAAAAGCCTGCCATATTCGAGCACCTGGGATCAACCCCACATGTGACGTGGCCTCCTCTCATGGACCAGCCTCTTCATCTGGCCAGACCACTTGACAACACGAGAGCTTACTTAGTATTAGCTATAGGAGTAGCGAGTGCATTGTTCCTCTATACACTAACCCGTAATACCCTTCCACACACCGGCGACAACATCCACCATTTACCGCACGGGGGTAGGTACGTGGACGGCACCAAAGGAATTCTCTACAACAGCCCCACCTCCTCATACCCATCCTCATCTCTCCCATTCTCCATGGTTATCGCACTAGCCACAACCCTTTTCCTCATCACCAGAAACATTCTCAACCCAGCCCCCACCACACCTAGAATCTATGCGCCCCTCTGCTTGCATTGTCACCGGAATCACCCACCATGCTAAACACTGACACACTATGCATCATTCTGTTCATACTAATATTAGGCATCCTATATAATATACTTCAACAGCATCTGCCCCCACCATGTGAAATAATAATAAACGGGCACACTATATCCATTAGGGGCAACTGCTACCACACCACCTCCAGCTAGGGTTTGTTAAGTTTCCCTTTTTGTAAATTAAACACTAAAGATGTCTGGAACTGGAACGGGAACTGGGCGAGGGACCGGGACAGGAGTAGGAGGCACTGGAGGCACAGGTGGCACAGGCGGCGGAGGAACAGGTAGAGGGCAACAAGCTGCACCCCAGCCCTGGGAAACAAAGTTCACTAAGGACGACCTGGCCGCAATCGAGCCAAAACCTGCTTCGGCAAATGTTCCAAACACTAAGCAGTGGATCAGCATTCAAGCTGGACTCATCAAGGCTGGAGCCACGGACGCAAACTTCATGAAAGTACTGCTCGGCCTCAGTCTCGAAGCTTTCGACAGGGGCTCGTCGGAGGCCACCACTTGGGATGGAATTACTGAGGGCGTGGAGCACCGTGCAGCAGCCAACGCCATCAAGGAGGCGAACTGCCCAATACACAAGGTCACCTACTACCTAGCCAAACCGACGTTCGCCATTAGACAATCGAAAAACCTCCCCCCAGCGAACTTCGCGAAGAAGAATGTGCCATCACAATATAAATGGTGTGCGTTCGATGCTTTTGATGGCCTGTACGATCCCACCTGCCTTGCCTCAGAACTACCCTACGACGCCCCCTCAGAAATAGACCGAATGGCGTCCGCTACCTTCAAAACTATACAGATCAAGATCGCTAATGACCAGAAAGGGTTCAACCTCAACTACAACCCTAACGTCACCCAGGCTCGACTCCCCAACGCGCCCCTACCAGCTCTTCCCGAACCAACATCAGACTAAACGTTGCATGATCGTAAAACATGCCCGGCTTACCGTGAGCCGCCTTTGAAAGAAAGGTTTACACGGACTCTGTTGCGTTACGCACGTACCTAACCCGTGCCAGCAGAATAAAGACCTTTTGGTTTCTACAGTTTTTTCCA",
        }
    ]

    await write_sequences(isolate_path, sequences)

    with open(sequence_path, "r") as f:
        assert json.load(f) == sequences[0]


def test_cache():
    write_cache(
        {
            "665102": [
                {
                    "id": "un404hxp",
                    "source_type": "unknown",
                    "source_name": "unknown",
                    "default": True,
                }
            ],
            "438782": [
                {
                    "id": "4e8amg20",
                    "source_type": "isolate",
                    "source_name": "Q767",
                    "default": True,
                },
                {
                    "id": "mzojjjmz",
                    "source_type": "isolate",
                    "source_name": "Q1108",
                    "default": False,
                },
            ],
            "190811": [
                {
                    "id": "ae7vj1om",
                    "source_type": "unknown",
                    "source_name": "unknown",
                    "default": True,
                }
            ],
            "35286": [
                {
                    "id": "lm3xmhrf",
                    "source_type": "isolate",
                    "source_name": "BaMV-O",
                    "default": True,
                }
            ],
        }
    )

    update_cache(
        {
            "2060511": [
                {
                    "id": "0f6",
                    "source_type": "isolate",
                    "source_name": "Tandapi",
                    "default": True,
                }
            ]
        }
    )

    assert get_cache() == {
        "665102": [
            {
                "id": "un404hxp",
                "source_type": "unknown",
                "source_name": "unknown",
                "default": True,
            }
        ],
        "438782": [
            {
                "id": "4e8amg20",
                "source_type": "isolate",
                "source_name": "Q767",
                "default": True,
            },
            {
                "id": "mzojjjmz",
                "source_type": "isolate",
                "source_name": "Q1108",
                "default": False,
            },
        ],
        "190811": [
            {
                "id": "ae7vj1om",
                "source_type": "unknown",
                "source_name": "unknown",
                "default": True,
            }
        ],
        "35286": [
            {
                "id": "lm3xmhrf",
                "source_type": "isolate",
                "source_name": "BaMV-O",
                "default": True,
            }
        ],
        "2060511": [
            {
                "id": "0f6",
                "source_type": "isolate",
                "source_name": "Tandapi",
                "default": True,
            }
        ],
    }
