from pathlib import Path

TEST_FILES_PATH = Path(__file__).parent / "files"
VFAM_INPUT_PATH = TEST_FILES_PATH / "input"
VFAM_INTERMEDIATES_PATH = TEST_FILES_PATH / "intermediates"

DUPES_INPUT = VFAM_INPUT_PATH / "Dupes"
GENERIC_INPUT = VFAM_INPUT_PATH / "Generic"
LARGE_INPUT = VFAM_INPUT_PATH / "Large"

DUPES_INTERMEDIATES = VFAM_INTERMEDIATES_PATH / "Dupes"
GENERIC_INTERMEDIATES = VFAM_INTERMEDIATES_PATH / "Generic"
LARGE_INTERMEDIATES = VFAM_INTERMEDIATES_PATH / "Large"
