name: "AUTO: Add new OTU"
on:
  issues:
    types: [labeled]
  
jobs:
  parse-otu-form:
    if: github.event.label.name == 'addition-otu'
    runs-on: ubuntu-latest
    outputs:
      taxon-id: ${{ steps.issue-parser.outputs.issueparser_taxid }}
      accessions: ${{ steps.issue-parser.outputs.issueparser_accessions }}
      
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: stefanbuck/github-issue-parser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/add_species.yaml

      - run: cat ${HOME}/issue-parser-result.json
          
      - run: |
          echo $TAXID
          echo $ACCESSIONS
        env:
          TAXID: ${{ steps.issue-parser.outputs.issueparser_taxid }}
          ACCESSIONS: ${{ steps.issue-parser.outputs.issueparser_accessions }}
  
  trigger-otu-addition:
    needs: parse-otu-form
    uses: ./.github/workflows/call__add_otu.yml
    with:
      taxon-id: ${{ needs.parse-otu-form.outputs.taxon-id }}
      accessions: ${{ needs.parse-otu-form.outputs.accessions }}
      debug: true
    permissions:
      contents: write
    secrets:
      GH_REF_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    