name: virtool_cli

on:
  pull_request:
    branches: [ master ]
  push:
    branches: "*"

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.8-buster
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip install -r requirements.txt

      - name: Test with pytest
        run: |
          pytest -x --cov --cov-report xml

      - uses: actions/checkout@master
      - name: Run codacy-coverage-reporter
        if: ${{ github.event_name == 'push' }}
        uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: cobertura.xml
